### PR TITLE
Added space between previous, next and the diagram in boolean algebra notes.

### LINKED ISSUE #391: Previous and next buttons
## Describe the bug
Previous and Next buttons on the page Boolean Algebra

## Expected behavior
Must be present in the next line with space in between

## Screenshots
image

## Additional context
I am not working on this bug

### PR DESCRIPTION
**Pull request by i-m-vivek**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #391 

Ref #

#### Changes done:
- [x] Added space between the interactive diagram and the previous & next buttons.

#### Screenshots
**OLD**
old
**NEW**
Capture

#### Preview Link(s): 
https://deploy-preview-393--tender-ardinghelli-ebb79f.netlify.app/docs/bool

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by i-m-vivek** [comment]
> Add the review link @i-m-vivek

Hey @abhinavsri360 I am new to open-source can you tell me what do you mean by a review link.

**Comment by abhinavsri360** [comment]
Sure why not @i-m-vivek 
Follow the steps:
In the checkbox where your request has passed all the checks i.e.,
image
Go to the details of 'Pages changes'
There you can find the line 'Changes pages include'
image
Click on view
A new link will open after you click on that, that's the link we are requesting for, copy the same and add that to you PR template here via editing:
image

**Comment by abhinavsri360** [comment]
@i-m-vivek review link is basically a link which portrays the changes which you have made on the project and how will it affect the project, it helps reviewers like us to examine and approve the changes that you have made.
I hope this helps.

**Comment by i-m-vivek** [comment]
@abhinavsri360 Thanks for the guide. Added preview links.

**Comment by abhinavsri360** [comment]
Looks good to me, though this bug can be triggered again I don't know why is it happening try figuring out why @i-m-vivek 
{
Open the preview link on your phone in chrome browser.
Change the view to desktop view.
Scroll to bottom, you may find no space between the buttons
}
I have no idea why is this happening. Try looking into this.

**Comment by YashKumarVerma** [comment]
Just checked, the changes are deployed.
image
However, we have a horizontal line for some reason there. That'll be fined in another pr.

**Comment by YashKumarVerma** [comment]
Thanks for your work @i-m-vivek @abhinavsri360.
Wishing you best of luck for OSS journey @i-m-vivek

**Pull request merged**
