### PR TITLE
Added FSM without output

### PR DESCRIPTION
**Pull request by ShreyaPrasad1209**

### CODE REVIEW

**Comment by ShreyaPrasad1209** [comment]
Added YouTube link in references

**Comment by ShreyaPrasad1209** [comment]
Your original content is a copy of https://www.tutorialspoint.com/digital_circuits/digital_circuits_finite_state_machines.htm. I'll edit mine.

**Comment by eKuG** [comment]
@tachyons @satu0king I feel we should write original content or somewhat derived. The original content seems to be highly based on the above mentioned website. Please look into it.

**Comment by tachyons** [comment]
In that case we need to edit original content as well, tutorial point terms states

> You are not allowed to translate, republish, or print the content of this website without a written permission from the company.

cc @Amansingla97

**Comment by eKuG** [comment]
In that case, Lets edit the whole book then! I have a distinguished background in Digital Electronics and so does @ShreyaPrasad1209 . I feel you should give us a chance?

**Comment by tachyons** [comment]
Removing copyrighted content and rewriting it is a great idea 👍  cc @satu0king

**Comment by aayush-05** [comment]
Hey !
I can too help with the content. Coming from an electronics background and being a freelancer at Tutorials Point itself; I can help to write plagiarism free content.
Do let me know if we are editing the whole content @tachyons

**Comment by ShreyaPrasad1209** [comment]
Should I leave the examples as it is? I don't think they count as plagiarism, since many online tutorials share same examples. @tachyons @satu0king

**Pull request closed without merging**
