### PR TITLE
Sidebar logo fixed for child pages

### LINKED ISSUE #236: Issue with Sidebar button in some pages
- [x] [Interactive Karnaugh Map](https://learn.circuitverse.org/docs/kmapi.html) - Doesn't have a sidebar button. 
- [ ] [Half Adder](https://learn.circuitverse.org/docs/Combinational/half_adder.html) - Doesn't have the icon in sidebar button.

### PR DESCRIPTION
**Pull request by abhinavsri360**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #
There was an issue with the sidebar button in some pages i.e., the button was not uniform across all pages. I have fixed the issue by copying the assets folder in docs directory because I discovered that while the page loaded there were some error logs in the console which expected js libraries to be in the docs folder. So I just made that happen.
Closes #236 
Ref #

#### Changes done:
Fixed sidebar button on the child pages.

#### Screenshots
After Changes
image

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
There is an inactive PR present, for which I asked to work yesterday. Number 237 by Ryuk
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
https://5ec660e38b30f3000797ad5a--tender-ardinghelli-ebb79f.netlify.app/
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by abhinavsri360** [comment]
I have made a new branch and made the request from that now this request can be reviewed,
@YashKumarVerma @abstrekt  @ShubhankarKG

**Comment by ShubhankarKG** [comment]
I'm not sure what you meant by error logs. The sidebar issue was already resolved in #297 . Also, the assets needs to be outside the docs folder. That's how a jekyll directory structure works. You might want to resolve that

**Comment by ShubhankarKG** [comment]
> This is Working Fine for all the Child Pages. But I want to confirm that do we require these Many File Changes to fix this issue?

Those many files are due to copying the entire assets folder into the docs folder

**Comment by abhinavsri360** [comment]
@Shivansh2407 by error logs I mean that there were some error generated on the console when pages with child were loaded which expected to load js from assets from the docs directory which were not present. As far as #237 is concerned I was not able to locate those files and I tried my way out. Hound not talks about the js indentation which was not created by me initially, even though I can try to resolve that but, that's a load of javascript and won't affect the implementation.
@ShubhankarKG the sidebar issue is not resolved and is wrongly rendered in the child pages. You can toggle to the Multiplexer page and see that on the hosted site. I repeat, the issue is still not resolved.

**Comment by abhinavsri360** [comment]
@ShubhankarKG you can have a look. This is a snippet from the hosted site and the sidebar logo is not correctly rendered. You can also look at the logs by running interactive-book on your local machine it'll definitely throw an error.

**Comment by ShubhankarKG** [comment]
I wasn't trying to demean you or anything, so apologies if I sounded rude. And I guess I figured out the solution to it as well. Instead of putting the assets folder inside, just remove all nested files and put them in the main docs folder. The folders like Combinational, MSI are causing such an issue. This idea is much more feasible, don't you think ?

**Comment by abhinavsri360** [comment]
Not to worry, you were not rude.
In case we move all the respective files in the docs folder then this might turn a headache for us because for that we will have to fix the header of all these pages along with the child pages of these pages, further changing the permalink and nav-order. This will create loads of confusion and we might end up breaking the site or may consume more time just to fix the logo. Instead we should give what the page requires i.e., assets directory in docs directory this is far less time consuming and we do not end up doing loads of confusing work.

**Comment by ShubhankarKG** [comment]
I was only debating because assets as a folder should not be inside another folder. Your solution indeed works, but i'm totally not sure if that is ideal. Anyways, I rest my case here.

**Comment by abhinavsri360** [comment]
I tried making changes in he same assets folder but that was resulting in relative file location error. So I thought about providing an efficient solution to this bug. That's why I added a sub-directory for the same. Let's wait for others to review.

**Comment by abhinavsri360** [comment]
Waiting for review @YashKumarVerma @Shivansh2407

**Comment by abhinavsri360** [comment]
In that case we might need to change header files of all files present in msi, register, flip-flops...etc and move them into docs directory along. Please let me know what issues that can cause.
@YashKumarVerma

**Comment by YashKumarVerma** [comment]
> In that case we might need to change header files of all files present in msi, register, flip-flops...etc and move them into docs directory along. Please let me know what issues that can cause.
> @YashKumarVerma

why do we need to move everything to `/docs`

**Comment by abhinavsri360** [comment]
because child pages expect js dependencies to be present in docs directory when called that's why we need to move assets to docs.

**Comment by ShubhankarKG** [comment]
That's still a lot of copy material. Are you sure there isn't another way ?

**Comment by abhinavsri360** [comment]
I tried other ways such as creating another layout for child pages but that didn't worked correctly and from my point of view I tried out but didn't worked. I find this an optimal solution to this problem.
In case we move child pages to the directory in which their parent is present i.e., docs then indentation of sidebar will be disrupted.
That's why I propose this solution.

**Comment by ShubhankarKG** [comment]
All child pages have a __parent__ tag, which can be accessed via the __page.parent__ tag. Maybe you can use an if else construct to properly align the relative links. You can cross check from your **_site** folder, just check if the correct links are being rendered.

**Comment by YashKumarVerma** [comment]
@JoshHeng what do you think about it ?

**Comment by abhinavsri360** [comment]
> All child pages have a **parent** tag, which can be accessed via the **page.parent** tag. Maybe you can use an if else construct to properly align the relative links. You can cross check from your **_site** folder, just check if the correct links are being rendered.

I will try this and let you know if this works.

**Pull request closed without merging**
