### PR TITLE
added toc in latches submodules

### PR DESCRIPTION
**Pull request by Dishebh**
#### Changes done:
- [x] Added toc in latches submodules and removed title from toc in flip-flops submodules.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Dishebh** [comment]
@abhinavsri360 there are toc in flip-flops' section, so I thought there should be one in latches' as well. Also, the amount of content could increase in the future, and then toc.will offer a great help for navigation.

**Comment by abhinavsri360** [comment]
Agreed!
image
I think here, instead of State Table we should use Truth Table as we did in other modules. Mentioning State Table of abs Latch Makes the title long. Let me know your views.

**Comment by Dishebh** [comment]
@abhinavsri360 I guess the state tables and the truth tables are both different things. Please check out this [link](https://www.quora.com/What-are-the-differences-between-a-state-table-an-excitation-table-and-a-truth-table)

**Comment by abhinavsri360** [comment]
Ohh my bad. Still, can you cut that out to State Table as the page is specific to x Latch and just mentioning State Table is Enough

**Comment by Dishebh** [comment]
@abhinavsri360 updated the titles :+1:

**Pull request merged**
