### PR TITLE
Scroll enabled in search bar (#447)

### LINKED ISSUE #447: Enable scrolling in search drop-down
## Describe the bug
Whenever the user types something in the search bar, It shows a long list of pages, extending the current page length. 

## To Reproduce

1.  Go to 'learn.circuitverse.org'
2.  Click on 'Search'
3.  Type Something in the search bar
4.  See error

## Expected behavior

We should enable vertical scrolling, showing maximum of 5 results at a time so that the drop-down does not stretches the page and also looks good to the user.

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

### PR DESCRIPTION
**Pull request by shubhdeep123**
Enabled scrolling in search drop-down  

Fixes #447 

#### Changes done:
- [x] Changed Search bar Property

 Screenshot from 2020-07-03 01-51-02

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by shubhdeep123** [comment]
@Shivansh2407 @YashKumarVerma 
please review

**Comment by b30wulffz** [comment]
Please add a preview link as the link generated by GitHub action is not having this feature: https://deploy-preview-448--tender-ardinghelli-ebb79f.netlify.app/

**Comment by shubhdeep123** [comment]
@b30wulffz I think we should shorten the width of search bar it would look more better, as long search bar cover a lot of heading section. What do you say ? 
Will it be good @YashKumarVerma and @Shivansh2407 ?

**Comment by tachyons** [comment]
`_site_` is dynamically generated style and you shouldn't be touching that file

**Review by coding-CEO — CHANGES_REQUESTED** [review]
You must not change any file in "/_site" Folder. Files in this folder are dynamically generated.
as told by @tachyons.

**Pull request closed without merging**
