### PR TITLE
Migrate to Netlify  !

### PR DESCRIPTION
**Pull request by Ananthavijay**
GCI task: https://codein.withgoogle.com/dashboard/task-instances/4772222330208256/
Fixes: https://github.com/CircuitVerse/Interactive-Book/issues/109
Preview: https://hardcore-hoover-332f7d.netlify.com/

- I have deployed another branch "deploy " of my fork in netlify and the link is added above.
- I have made my Pull request from another branch " Netlify "
- Disqus does not get loaded in my deploy. I think it is not a problem as, to use Disqus first it should be registered which I have not done. So I think there won't be any problem when Interactive-Book is deployed in http://learn.circuitverse.org/

Cheers 🍻

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@tachyons @ankitkataria @satu0king Please review

**Comment by Ananthavijay** [comment]
and should I delete CNAME as it is useless after deploying this on netlify

**Comment by satu0king** [comment]
> and should I delete CNAME as it is useless after deploying this on netlify

@Ananthavijay Netlify is meant to be used for development and not deployment at least for now. So no please don't delete the CNAME record

**Comment by satu0king** [comment]
> and should I delete CNAME as it is useless after deploying this on netlify

@Ananthavijay Netlify is meant to be used for development and not deployment at least for now. So no please don't delete the CNAME record. Yes Disqus has been configured to work only on learn.circuitverse.org

**Pull request merged**
