### PR TITLE
[GSoD2020] Site URL Fixes + Gitpod!

### LINKED ISSUE #78: Setup Gitpod for this project
Gitpod helps to make development and reviewing PRs easier by proving cloud IDE. Having Gitpod setup for this repo will be great

### PR DESCRIPTION
**Pull request by manjotsidhu**
This Pull Request deals with the issues of Site Configuration URL which led to these problems :
- [x] Gitpod Development Previews (Added `.gitpod.yml` as well)
- [x] Netlify Production/Branch/Pull Request Deploy Previews.
- [x] GitHub Codespaces Development Previews (Using custom env variable)
- [x] Customize site URL by using `CV_SITE_URL` for development purposes.

Fixes #78
Ref #374, #154 

#### Changes done:
- [x] Custom plugin to set site URL before building (this overrides `url` variable in config)
- [x] Added .gitpod.yml configuration
- [x] Added `CV_SITE_URL` note in `README.md` 
- [x] Add Open in Gitpod instructions in `README.md`

#### Preview Link(s): 
Gitpod: http://gitpod.io/#https://github.com/manjotsidhu/Interactive-Book/
Netlify: https://deploy-preview-529--learncircuitverse.netlify.app/

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by manjotsidhu** [comment]
@Shivansh2407 @tachyons Kindly review.

**Comment by tachyons** [comment]
This is cool, thanks

**Comment by tachyons** [comment]
Reverting this for now as this broke the betalearn website, we may have to use https://docs.netlify.com/configure-builds/file-based-configuration/ ENV vars on netlify toml file

**Comment by manjotsidhu** [comment]
> Reverting this for now as this broke the betalearn website, we may have to use https://docs.netlify.com/configure-builds/file-based-configuration/ ENV vars on netlify toml file

Site deployments are done using netlify ?

**Pull request merged**
