### PR TITLE
NOR and XOR Descriptions Fixed

### LINKED ISSUE #161: Incorrect NOR and XOR Descriptions
In the logic gates section, the NOR and XOR gates are a complete copy of the NAND gate. The XOR and NOR gates have the correct CircuitVerse example and truth tables, but their descriptions are an exact copy and paste of the NAND description.

NAND
NOR
XOR

**Are you working on this?**
Yes

### PR DESCRIPTION
**Pull request by NumberC**
Fixes #161 
NOR
XOR

### CODE REVIEW

**Comment by NumberC** [comment]
@tachyons @ankitkataria Can you please merge this?

**Comment by NumberC** [comment]
Done

**Comment by aayush-05** [comment]
Remove the unrelated changes @NumberC . No need to change jquery assests with cdn and bypass netlify error.

**Comment by NumberC** [comment]
@aayush-05 Is this better?

**Comment by aayush-05** [comment]
Remove the change regarding the jquery version as well.

**Comment by NumberC** [comment]
@aayush-05 Sorry about that. This should be better

**Comment by aayush-05** [comment]
Looks good to me @NumberC . We can merge this now @tachyons

**Pull request merged**
