### PR TITLE
added gates images in gates.md

### PR DESCRIPTION
**Pull request by Dishebh**
--- added gates images in gates.md

## ✅️ By submitting this PR, I have verified the following

* [x] Checked to see if a similar PR has already been opened 🤔️
* [x] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Comment by Dishebh** [comment]
> Good work, but how about using circuit-verse components for the same?
> 
> I think it would be more apt if we use the component pictures as in simulator. there're available in the circuitverse/circuitverse repository.
> 
> What do you think?

Shall I add the svg of the gates present in the circuitverse/circuitverse repo to this repo and make changes accordingly? Either way, if we have to add the images to this repo, I guess if we add it from another repo or download from google, it should not make much difference.
@YashKumarVerma thoughts?

**Comment by YashKumarVerma** [comment]
> > Good work, but how about using circuit-verse components for the same?
> > I think it would be more apt if we use the component pictures as in simulator. there're available in the circuitverse/circuitverse repository.
> > What do you think?
> 
> Shall I add the svg of the gates present in the circuitverse/circuitverse repo to this repo and make changes accordingly? Either way, if we have to add the images to this repo, I guess if we add it from another repo or download from google, it should not make much difference.
> @YashKumarVerma thoughts?

Images from google are a third party, can be subject to copyright from where you get them. as for the ones from the main repo are concerned, they're of circuitverse.

**Comment by Dishebh** [comment]
> > > Good work, but how about using circuit-verse components for the same?
> > > I think it would be more apt if we use the component pictures as in simulator. there're available in the circuitverse/circuitverse repository.
> > > What do you think?
> > 
> > 
> > Shall I add the svg of the gates present in the circuitverse/circuitverse repo to this repo and make changes accordingly? Either way, if we have to add the images to this repo, I guess if we add it from another repo or download from google, it should not make much difference.
> > @YashKumarVerma thoughts?
> 
> Images from google are a third party, can be subject to copyright from where you get them. as for the ones from the main repo are concerned, they're of circuitverse.

From what I see,  there are no watermarks available on the images. If you want, I can download the images from the repo and add it here. Shall I do it?

**Comment by YashKumarVerma** [comment]
> > > > Good work, but how about using circuit-verse components for the same?
> > > > I think it would be more apt if we use the component pictures as in simulator. there're available in the circuitverse/circuitverse repository.
> > > > What do you think?
> > > 
> > > 
> > > Shall I add the svg of the gates present in the circuitverse/circuitverse repo to this repo and make changes accordingly? Either way, if we have to add the images to this repo, I guess if we add it from another repo or download from google, it should not make much difference.
> > > @YashKumarVerma thoughts?
> > 
> > 
> > Images from google are a third party, can be subject to copyright from where you get them. as for the ones from the main repo are concerned, they're of circuitverse.
> 
> From what I see, there are no watermarks available on the images. If you want, I can download the images from the repo and add it here. Shall I do it?

I'd recommend you to do it.

**Pull request closed without merging**
