### PR TITLE
Added different types of Synchronous and Asynchronous Counters 

### PR DESCRIPTION
**Pull request by Ananthavijay**
GCI task : https://codein.withgoogle.com/dashboard/task-instances/6562341051695104/

Preview: https://hardcore-hoover-332f7d.netlify.com/docs/counter.html

Screenshots : 

Screenshot (108)
Screenshot (106)
Screenshot (107)

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@sakshi1499 Please have a look

**Comment by sakshi1499** [comment]
Amazing work! @Ananthavijay .  @tachyons @ankitkataria this looks great to me! Should I approve it?

**Comment by tachyons** [comment]
LGTM, just confirm that images and content are not copied from anywhere else

**Comment by sakshi1499** [comment]
I have already confirmed regarding the images in the previous pull request that he closed to open this one. Regarding the content, I have searched it online on google couldn't find the same set of sentences anywhere. @tachyons

**Comment by sakshi1499** [comment]
I could find the ring counter one on google please update that @Ananthavijay. Change the sentence in your own way. The ring counter one is present on website. BCD one is fine, I couldn't find that anywhere

**Comment by Ananthavijay** [comment]
I drew the circuit diagrams in draw.io.
If you want I could even attach the source files of it

**Pull request merged**
