### PR TITLE
Boolean functions page content refactored

### LINKED ISSUE #56: Add POS and SOP
Add following topics after Boolean function-
1. Sum of Product
2. Product of Sum
3. Minimal to Canonical Form Conversion 

Explain with examples, diagrams, flow-charts etc.
 
You are expected to extend the content from here - https://learn.circuitverse.org/docs/bool2.html#sum-of-product-expressions-sop

### PR DESCRIPTION
**Pull request by abhinavsri360**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #
📝 
Boolean functions page refactored.
POS added.
K-mad page linked.
Examples enhanced.
This request enhances #80 
Closes #56 
Ref #

#### Changes done:
- [x] Task 1

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
An inactive PR is present, number 140
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
https://deploy-preview-315--tender-ardinghelli-ebb79f.netlify.app/docs/bool2
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by abhinavsri360** [comment]
Thank you so much @coding-CEO I have refactored the table 👍 
Preview link: https://deploy-preview-315--tender-ardinghelli-ebb79f.netlify.app/docs/bool2

**Comment by abhinavsri360** [comment]
waiting for review @YashKumarVerma

**Comment by abhinavsri360** [comment]
@Shivansh2407 con you review this?

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Comment by YashKumarVerma** [comment]
@coding-CEO  @abhinavsri360  I think the PR template should be filled properly.

**Comment by abhinavsri360** [comment]
Will take care of the template by next time.

**Pull request merged**
