### PR TITLE
Corrected grammatical errors of application.md

### PR DESCRIPTION
**Pull request by Dishebh**
#### Changes done:
- [x] Corrected grammatical errors and made `application.md` prettier.

Preview Link: https://deploy-preview-301--tender-ardinghelli-ebb79f.netlify.app/

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
> #### Changes done:
> * [x]  Corrected grammatical errors and made `application.md` prettier.
> 
> ####  By submitting this PR, I have verified the following
> * [x]  Checked to see if a similar PR has already been opened thinking
> * [x]  Reviewed the contributing guidelines mag
> * [x]  Sample preview link added (add a link from the checks tab after checks complete)
> * [x]  Tried Squashing the commits into one

sample preview link added ?

**Comment by Dishebh** [comment]
> > #### Changes done:
> > 
> > * [x]   Corrected grammatical errors and made `application.md` prettier.
> > 
> > #### By submitting this PR, I have verified the following
> > 
> > * [x]   Checked to see if a similar PR has already been opened thinking
> > * [x]   Reviewed the contributing guidelines mag
> > * [x]   Sample preview link added (add a link from the checks tab after checks complete)
> > * [x]   Tried Squashing the commits into one
> 
> sample preview link added ?

Done. Actually, I was waiting for all the checks to pass.

**Comment by YashKumarVerma** [comment]
I'll recommend a bit more meaningful PR title.

**Comment by YashKumarVerma** [comment]
@coding-CEO @Dishebh @abhinavsri360 
you guys might be thinking that I'm being too strict in merging works, but believe me, once you get the taste of quality collaboration, you'll understand the reasons for this.

**Comment by abhinavsri360** [comment]
Not at all. I am comfortable with what you say as what is right is right.

**Comment by Dishebh** [comment]
> @coding-CEO @Dishebh @abhinavsri360
> you guys might be thinking that I'm being too strict in merging works, but believe me, once you get the taste of quality collaboration, you'll understand the reasons for this.

Nope, not at all. You're doing a great job! And thank you for this :rocket:

**Comment by coding-CEO** [comment]
> @coding-CEO @Dishebh @abhinavsri360
> you guys might be thinking that I'm being too strict in merging works, but believe me, once you get the taste of quality collaboration, you'll understand the reasons for this.

We all are here to Learn.
Thanks for this taste of quality collaboration.

**Pull request merged**
