### PR TITLE
Add next and previous buttons

### LINKED ISSUE #73: Add Next and Prev option
**Problem**
Right now there's no link(apart from side navbar) which directs user from one page to another. Like in a book we can turn to next/prev page, we can do this in Interactive Book too.

**Proposed Solution**
Add a Next and Prev link in each page which will redirect the user to relevant page.
**Screenshot** 

Add this link above comment section

**Are you working on this task?**
No, for GCI participants under medium

### PR DESCRIPTION
**Pull request by JoshHeng**
Fixes #73 

Added previous and next buttons which allow the user to advance through the whole interactive book with one button.

### CODE REVIEW

**Comment by JoshHeng** [comment]
I don't believe that netlify is set up to build .scss files. I've added some code in `navigation.scss` which styles the buttons and it shows up on my local instance, however on Netlify the css file `just-the-docs.css` that is built doesn't mention it at all.

```scss
.navbar {
  display: flex;
  justify-content: space-between;
}
```

**Comment by JoshHeng** [comment]
That's how it's supposed to look

**Comment by JoshHeng** [comment]
I've just done some testing and if I execute `bundle exec jekyll build` the scss won't be compiled, but if I execute `bundle exec jekyll serve` it will.
Anyway, I've just added the styling on the webpage itself in `<style>` brackets

**Comment by deepak2431** [comment]
@JoshHeng The changes looks fine to me. But I think it's good to have the styling in .scss file than in the default.html. Can you please make those changes and update the PR?

**Comment by JoshHeng** [comment]
@deepak2431 there is some styling in the .scss file which is loaded on `bundle exec jekyll serve`, but not on a build.
See comments above

**Comment by aayush-05** [comment]
Hey @JoshHeng 
Adding changes in the .scss files and then running `bundle exec jekyll serve` would show the changes in your local server; running that command automatically builds a new sass cached file to be used.
It won't be an issue if netlify doesn't show the changes, because anyways it doesn't support jekyll.

**Comment by JoshHeng** [comment]
> 
> 
> Hey @JoshHeng
> Adding changes in the .scss files and then running `bundle exec jekyll serve` would show the changes in your local server; running that command automatically builds a new sass cached file to be used.
> It won't be an issue if netlify doesn't show the changes, because anyways it doesn't support jekyll.

Yes, `bundle exec jekyll serve` shows the built css file however when the repo is actually built/deployed with `bundle exec jekyll build`, the css file is not updated.

Netlify does support jekyll and uses `jekyll build` to deploy the preview - the commands it follows are shown in the following link: https://app.netlify.com/sites/tender-ardinghelli-ebb79f/deploys/5e07a24f26f07e00082a874d

**Comment by deepak2431** [comment]
@aayush-05 I have checked the preview deploy it works perfectly. What do you think? I think I shall approve his task now.

**Comment by aayush-05** [comment]
Oh, sorry I got confused between jekyll and rails @JoshHeng .
Remove the additional code you added in the main html file, I guess the things would then also be working as expected on your local server ?
No problem if netlify doesn't load it. Netlify must be using the `bundle exec jekyll build` command, it creates a new build but continues to deploy the server on the basis of the previous build only until you explicity mention it.
And also I think you wanted to add the `btn-info` class for the previous button
image

**Comment by aayush-05** [comment]
Once these changes are done, we would be ready to approve the task @deepak2431

**Comment by deepak2431** [comment]
@JoshHeng Looks good to me now.

**Comment by Shivansh2407** [comment]
Please fix the merge conflicts @JoshHeng

**Comment by JoshHeng** [comment]
@Shivansh2407 Fixed conflicts, please merge

**Comment by JoshHeng** [comment]
Please see #340

**Pull request closed without merging**
