### PR TITLE
Added Bidirectional Shift Register and Universal Shift Register

### LINKED ISSUE #36: Add other two registers
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
Currently, the book only consists of 4 types of registers. The other two missing registers which should be added are
1. Bidirectional Shift Register
2. Universal Shift Register

### PR DESCRIPTION
**Pull request by Prerna-0202**
Fixes #36

#### Changes done:
-  I have added  Bidirectional Shift Register and Universal Shift Register as per issue number #36 

#### Screenshots->
Screenshot (54)
Screenshot (52)
Screenshot (53)

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Prerna-0202** [comment]
@manjotsidhu , Can you please review my pr and provide me with the feedback...

**Review by ayan-biswas0412 — APPROVED** [review]
Looks fine to me 🎉
Good work @Prerna-0202 🚀

**Comment by Prerna-0202** [comment]
@ayan-biswas0412, Thanks for reviewing ...

**Review by manjotsidhu — APPROVED** [review]

**Review by manjotsidhu — CHANGES_REQUESTED** [review]
I am not able to see the images in deploy preview, can you check once ?
https://deploy-preview-590--vigilant-nightingale-2f57b2.netlify.app/docs/seq-msi/registers.html#bidirectional-shift-register

**Comment by ayan-biswas0412** [comment]
> I am not able to see the images in deploy preview, can you check once ? https://deploy-preview-590--vigilant-nightingale-2f57b2.netlify.app/docs/seq-msi/registers.html#bidirectional-shift-register

but in my preview images are showing nicely

**Comment by tachyons** [comment]
Hey, Can you confirm that the contents and the images are not copied from the internet ?

**Comment by Prerna-0202** [comment]
@manjotsidhu, I have commit the changes. Can you please review my pr once...

**Comment by manjotsidhu** [comment]
> Hey, Can you confirm that the contents and the images are not copied from the internet ?

@Prerna-0202

**Comment by manjotsidhu** [comment]
@ayan-biswas0412 Can you review the simulator embeds ?

Also, the embeds on mobile devices overflow the page. This bug is present everywhere and can be dealt separately in #593

**Comment by Prerna-0202** [comment]
> Hey, Can you confirm that the contents and the images are not copied from the internet?

Sir, actually I have read the concept from the internet but I didn't copy it from there. I wrote here, what I got after reading. I think still some lines are maybe the same as the internet. I will change that and will make a new commit with the whole content from my side...

**Comment by Prerna-0202** [comment]
@manjotsidhu I have commit the changes. Please review...

**Comment by Malavi1** [comment]
> Hey, Can you confirm that the contents and the images are not copied from the internet ?

@tachyons It is ok if we take the contents from the text book?

**Comment by tachyons** [comment]
No, we can't take content from copyrighted material including textbooks

**Comment by Malavi1** [comment]
Then, one actually will update the content

**Pull request closed without merging**
