### PR TITLE
Added information regarding Race around condition

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/CircuitVerse/Interactive-Book/issues/41
[GCI Task](https://codein.withgoogle.com/dashboard/task-instances/5955915132436480/)

- Added information regarding Race around condition in JK flip-flop
- All the images were drawn in draw.io

https://deploy-preview-215--tender-ardinghelli-ebb79f.netlify.com/docs/jk_race_around_condition.html

### Screenshots
Screenshot (205)
Screenshot (203)
Screenshot (204)

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Please review @aayush-05 @deepak2431

**Comment by aayush-05** [comment]
Can you make the table in markdown format rather than an image ?
Also, describe in brief the methods you have mentioned to eliminate Race around condition

**Comment by Ananthavijay** [comment]
I think that this table can't be made in markdown format.

**Comment by Ananthavijay** [comment]
Described the methods of elimination of race around condition in brief @aayush-05

**Comment by Ananthavijay** [comment]
Done @aayush-05

**Comment by Ananthavijay** [comment]
Updated the screenshots and all Done! @aayush-05

**Comment by aayush-05** [comment]
Looks like you have missed adding the link to this page in the sidebar. Please add a link there too @Ananthavijay

**Comment by Ananthavijay** [comment]
@aayush-05 The link is present in the sidebar.
Screenshot (206)
Can I submit the task for approval?

**Comment by aayush-05** [comment]
Yes, working fine on my local server. Might be some problem with netlify builds.
You can submit the task now @Ananthavijay

**Comment by Ananthavijay** [comment]
Done !

**Comment by aayush-05** [comment]
Good to be merged @tachyons

**Pull request merged**
