### PR TITLE
simulator fixed

### LINKED ISSUE #310: Simulator invisible in mobile view
## Describe the bug
The simulator present on the Boolean Algebra page is invisible for the mobile view.

## To Reproduce
reproduced in #390 

## Expected behavior
Should be visible on mobile view as well

## Screenshots
Screenshot_20200518-132052

I am working on this issue.

### PR DESCRIPTION
**Pull request by abhinavsri360**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #
Simulator was not visible in mobile view in the Boolean Algebra page which is now visible and Closes #310 
Ref #

#### Changes done:
Simulator view fixed

#### Screenshots
image

#### Preview Link(s): 
https://deploy-preview-390--tender-ardinghelli-ebb79f.netlify.app/docs/bool

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by abhinavsri360** [comment]
Sure @Shivansh2407 I'll fix the styling

**Comment by Shivansh2407** [comment]
Are you working on this @abhinavsri360 ?

**Comment by abhinavsri360** [comment]
Yes I am, was busy with University work and will fix this in awhile.

**Comment by abhinavsri360** [comment]
@Shivansh2407 I have made the changes and the simulator looks good now in the mobile view as well.
image
You can test the preview link as well here: 
https://deploy-preview-390--tender-ardinghelli-ebb79f.netlify.app/docs/bool

**Comment by abhinavsri360** [comment]
@Shivansh2407 waiting for review

**Comment by Shivansh2407** [comment]
@abhinavsri360 that is really awesome that we the simulator now available for mobile. Can you let me know your views on keeping the drop-down menu between the switches. I guess that would look more better.

**Comment by abhinavsri360** [comment]
Good idea I will try doing that as well.

**Comment by abhinavsri360** [comment]
@Shivansh2407 fixed the simulator view for mobile phones. This PR is now ready for merge here's the preview link: https://deploy-preview-390--tender-ardinghelli-ebb79f.netlify.app/docs/bool
image

**Comment by Shivansh2407** [comment]
Now it is looking much better @abhinavsri360 👍. Nice Work . Just some tweaks to the alignment of elements is required. Please have a look at the picture below for reference.
image

**Comment by abhinavsri360** [comment]
Ohh, my bad. will fix this.

**Comment by abhinavsri360** [comment]
selection in mobile fixed @Shivansh2407 
Preview:https://deploy-preview-390--tender-ardinghelli-ebb79f.netlify.app/docs/bool

**Comment by Shivansh2407** [comment]
You need to just align the bulb now. Then we will be good to go. The Gate selection looks better now in mobile view.
After you do all the commits make sure to squash them👍

**Comment by Shivansh2407** [comment]
Nice Abhinav, The simulator now looks perfect for mobile. Before you continue to squash. Please take a look at this and try removing the line also😅.
IMG_20200608_204008

**Comment by abhinavsri360** [comment]
I will fix buttons and squash commits in awhile.

**Comment by abhinavsri360** [comment]
Squashed all commits and here's the deploy link: https://deploy-preview-390--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html
Please let me know @Shivansh2407 if there are still any bugs.

**Pull request merged**
