### PR TITLE
Added XNOR Gate

### LINKED ISSUE #24: Add XNOR gate tutorial
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
 In the logic gates tutorial the tutorial for the XNOR gate is missing. Add the tutorial of XNOR gate to the section of logic gates.

### PR DESCRIPTION
**Pull request by NumberC**
Fixes #24 

XNOR

### CODE REVIEW

**Comment by deepak2431** [comment]
@NumberC Great work. It's good to me.
@tachyons @ankitkataria Please review it once if it's all good.

**Comment by NumberC** [comment]
@tachyons Is this good?

**Comment by NumberC** [comment]
I downloaded the latest version of the CircuitVerse repo. I guess the about page was changed in the repo.

**Comment by tachyons** [comment]
Rebase with latest master, You can refer this for syncing your fork, no need to download everytime https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by NumberC** [comment]
Oh. Thank you!

**Comment by aayush-05** [comment]
@NumberC looks like you have made all the PRs on the same branch, this can't be merged. Can you make a new PR with only the desired changes ?

**Comment by Shivansh2407** [comment]
@NumberC Please Make a New PR with the desired changes 👍 . Closing this because some unrelated changes are present too.

**Pull request closed without merging**
