### PR TITLE
[GCI] Add universal gates section

### LINKED ISSUE #27: Add title:universal gate
In logic gate section there no word saying what are universal gate and how we can use them to make all other logic gates

### PR DESCRIPTION
**Pull request by junron**
Fixes #27 

Added section on Universal gates and demonstrate how to implement NOT, OR and AND gates with each universal gate.

# Screenshot of Introduction
image

# Screenshot of implementing NOT and OR gate with NOR
image

# Screenshot of implementing AND gate with NOR
image

# Screenshot of NOT and OR gate with NAND
image

# Screenshot of AND gate with NAND
image

# Implementations embedded
## NOR gate
[not](https://circuitverse.org/users/11772/projects/45175)  
[or](https://circuitverse.org/users/11772/projects/45176)
[and](https://circuitverse.org/users/11772/projects/45177)

## NAND gate
[not](https://circuitverse.org/users/11772/projects/45178)
[or](https://circuitverse.org/users/11772/projects/45179)
[and](https://circuitverse.org/users/11772/projects/45180)

[GCI task](https://codein.withgoogle.com/dashboard/task-instances/5517828283695104/)

Please review @deepak2431 @sakshi1499

### CODE REVIEW

**Comment by sakshi1499** [comment]
@junron The mentor for this task is @deepak2431 . I have reviewed it and I hope all the content you have written is in your own words and that you haven't copied it? Implementation of all the gates is good. Can you mention somewhere that Not And and Or are basic gates?

**Comment by sakshi1499** [comment]
Also, if you aren't using netlify, please attach the screenshots in the description

**Comment by junron** [comment]
@sakshi1499 I have stated that NAND and NOR are universal gates in the second paragraph of the introduction.

Only the definitions of the NAND and NOR gates are adapted from the Gates page. All other explanations are written by me.

I will include screenshots soon. The embeds do not work on netlify

**Comment by junron** [comment]
@sakshi1499 I have added the screenshots as you requested. A sentence about AND, OR and NOT gates being basic was added. @deepak2431 Please review.

**Comment by sakshi1499** [comment]
Woah! Looks good to me @junron. @deepak2431 will review it once, he was the mentor for this task.

**Comment by deepak2431** [comment]
@junron Looks good to me. As you have mentioned the universal gates and implemented all other gates using Universal gate.
Thanks!

**Comment by aayush-05** [comment]
Good to be merged @tachyons

**Pull request merged**
