### PR TITLE
#242 Alignment Issue Fixed

### PR DESCRIPTION
**Pull request by coding-CEO**
I had already solved this #242  issue. but I think it got revert somehow. So, making this PR again.

## ✅️ By submitting this PR, I have verified the following

* [✅️] Checked to see if a similar PR has already been opened 🤔️
* [✅️] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Comment by mahmodHammad** [comment]
Why do you think it got reverted?

**Comment by coding-CEO** [comment]
> Why do you think it got reverted?

No Idea. But No worries, the problem is solved.

**Comment by coding-CEO** [comment]
@mahmodHammad you can merge this PR. It is same as #262 .

**Comment by YashKumarVerma** [comment]
this is rather strange, the old PR was not reverted

**Comment by coding-CEO** [comment]
I found it. Sorry it was my mistake.
This got reversed in this PR #264 . 
Now you can merge this PR.
It happened because of my lack of knowledge in git...

**Comment by coding-CEO** [comment]
> Merge conflicts

Solved Conflicts. Please Review.

**Comment by YashKumarVerma** [comment]
Please use different branches for different pull requests to avoid further issues like the one we faced here

**Comment by coding-CEO** [comment]
> Please use different branches for different pull requests to avoid further issues like the one we faced here

Definately. Sorry for inconvinience.

**Pull request merged**
