### PR TITLE
Redesigned list in Boolean Algebra dropdown

### LINKED ISSUE #290: List items in BooleanAlgebra.md
## Is your feature request related to a problem? Please describe.

No
The simulator present in the end which consists of the words 'AND', 'OR', 'XOR', and 'NOT' might not be a good option for presentation.
## Describe the solution you'd like

I propose to have a gate image along with its name present inside the gate image(can use SVG image for that) instead of gate name.

## Describe alternatives you've considered

Just have gate representation with the name of the gate in the center of that image. As the names present are quite big and look creepy.

## Additional context

I think the context above describes my problem well.

### PR DESCRIPTION
**Pull request by coding-CEO**
Added images to the design of list in boolean algebra. to improve UX.

Fixes #290 

Ref #
## Before:->
NPAVScSt (2)
NPAVScSt

## After:->
NPAVScSt (4)
NPAVScSt (3)

#### Changes done:
- [x] added image to the selected item in boolean algebra dropdown

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)

### CODE REVIEW

**Comment by coding-CEO** [comment]
Sample link:->
https://5ec22aa5e0e65e0006790dcd--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html

**Comment by coding-CEO** [comment]
Review @YashKumarVerma | @abhinavsri360

**Comment by abhinavsri360** [comment]
Drop-down list arrow is invisible, try to make that visible

**Comment by coding-CEO** [comment]
> Screenshot from 2020-05-18 12-36-32
> I think this can be improved a bit. what do you think ?

That is an issue with sample link.
Text is not invisible in original build.

**Comment by coding-CEO** [comment]
## Added arrow. @abhinavsri360 
screenshot - 5_18_2020, 1_28_19 PM

## See @YashKumarVerma The text is not invisible in original build.
screenshot - 5_18_2020, 1_24_12 PM

**Comment by coding-CEO** [comment]
Latest Sample link.
https://5ec240b6b4e1120007d0da11--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html

**Comment by Shivansh2407** [comment]
It would be better if you take the image of all the gates from CircuitVerse Simulator @coding-CEO 👍

**Comment by Shivansh2407** [comment]
> > Screenshot from 2020-05-18 12-36-32
> > I think this can be improved a bit. what do you think ?
> 
> That is an issue with sample link.
> Text is not invisible in original build.

Have you tried this on your localhost? Is it the same there? 
Actually I have seen the same drop-down through another preview link wherein the text was there instead of the images. There the drop-down options were visible. Please check once 👍

**Comment by coding-CEO** [comment]
> It would be better if you take the image of all the gates from CircuitVerse Simulator @coding-CEO

@Shivansh2407 Are you talking about these images ? But these images don't have name of logic gate.

a

**Comment by coding-CEO** [comment]
> > > Screenshot from 2020-05-18 12-36-32
> > > I think this can be improved a bit. what do you think ?
> > 
> > 
> > That is an issue with sample link.
> > Text is not invisible in original build.
> 
> Have you tried this on your localhost? Is it the same there?
> Actually I have seen the same drop-down through another preview link wherein the text was there instead of the images. There the drop-down options were visible. Please check once

@Shivansh2407  It is very hard to add the images of gates inside list. I can only add image once it is selected.
That is why I kept text inside list and I change the image of list once it is selected.

It looks like this in my localhost.
screenshot - 5_18_2020, 1_24_12 PM

**Comment by Shivansh2407** [comment]
Cool. If it is working fine in your localhost then it's good. I was not asking you to put images in the option instead of the text, I was asking regarding the invisible text issue and looks like it is working fine on your localhost.
Could you please post a screen recording of the working drop-down with images?

**Comment by Shivansh2407** [comment]
> > It would be better if you take the image of all the gates from CircuitVerse Simulator @coding-CEO
> 
> @Shivansh2407 Are you talking about these images ? But these images don't have name of logic gate.
> 
> a
> 

I guess having the Images from CircuitVerse would be better. Also the text is there on the option in the drop-down so it should not be a problem.
Let me know your views.

**Comment by coding-CEO** [comment]
> > > It would be better if you take the image of all the gates from CircuitVerse Simulator @coding-CEO
> > 
> > 
> > @Shivansh2407 Are you talking about these images ? But these images don't have name of logic gate.
> > a
> 
> I guess having the Images from CircuitVerse would be better. Also the text is there on the option in the drop-down so it should not be a problem.
> Let me know your views.

My view would be to keep this as it is, because if some user don't know how each logic gate looks like. So, every time clicking on the drop-down list name to see which gate is selected would lead to bad user experience.

**Comment by coding-CEO** [comment]
> Cool. If it is working fine in your localhost then it's good. I was not asking you to put images in the option instead of the text, I was asking regarding the invisible text issue and looks like it is working fine on your localhost.
> Could you please post a screen recording of the working drop-down with images?

Yeah. It is working fine on my localhost.

Actually there is electricity issue in our area. So, my PC is off. So, I will be able to share the screen recording later. I hope it's fine with you @Shivansh2407.

**Comment by coding-CEO** [comment]
> Cool. If it is working fine in your localhost then it's good. I was not asking you to put images in the option instead of the text, I was asking regarding the invisible text issue and looks like it is working fine on your localhost.
> Could you please post a screen recording of the working drop-down with images?

@Shivansh2407 @YashKumarVerma Checkout this video of my localhost.
ezgif com-video-to-gif

If you all are satisfied now, I think this PR can be merged...

**Comment by Shivansh2407** [comment]
Nice Work @coding-CEO 👍 . Just a small suggestion, I think we should change the NOT Gate to match the theme of the rest of the gates in the option. Let me know your views .

**Comment by coding-CEO** [comment]
> Nice Work @coding-CEO  . Just a small suggestion, I think we should change the NOT Gate to match the theme of the rest of the gates in the option. Let me know your views .

I can do that, but there is no such image available in the project.
So, I have to download that type of image from internet.

**Comment by Shivansh2407** [comment]
NOT_gate
How about this @YashKumarVerma ?

**Comment by coding-CEO** [comment]
How about this @Shivansh2407 ????
NPAVScSt

**Comment by Shivansh2407** [comment]
Yes👍 . Go ahead and commit.

**Comment by Shivansh2407** [comment]
Yes👍

**Comment by coding-CEO** [comment]
latest sample link
https://5ec3680b63c29a0006be3a12--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html

**Comment by coding-CEO** [comment]
> Nice work  @coding-CEO

Thanks !

**Pull request merged**
