### PR TITLE
Highlighted all notes for better readability

### PR DESCRIPTION
**Pull request by Dishebh**
#### Changes done:
- [x] Highlighted all notes for better readability.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Please consider switching branches for every new PR from time. Please squash the commits for this time.

**Comment by Dishebh** [comment]
@ShubhankarKG @Shivansh2407 I tried squashing but I messed up my branch. Can you please help me with it?

**Comment by ShubhankarKG** [comment]
Okay, so I think you'll have to open a new PR now. Follow these steps.

1. Remember what changes you made. Note it down somewhere.
2. `git checkout master`.
3. `git pull origin master`.
4. `git checkout -b your_branch_name`.
5. Perform all __your__ changes.
6. `git commit -am "Commit message"`.
7. `git push upstream your_branch_name`.

Then open a new PR.

**Comment by Dishebh** [comment]
> Okay, so I think you'll have to open a new PR now. Follow these steps.
> 
> 1. Remember what changes you made. Note it down somewhere.
> 2. `git checkout master`.
> 3. `git pull origin master`.
> 4. `git checkout -b your_branch_name`.
> 5. Perform all **your** changes.
> 6. `git commit -am "Commit message"`.
> 7. `git push upstream your_branch_name`.
> 
> Then open a new PR.

Sure, thanks!

**Comment by Dishebh** [comment]
@ShubhankarKG I tried the last step, but the following error showed up:
`fatal: 'upstream' does not appear to be a git repository`

I also tried `git push -u origin <branch_name>`, but the case turned out to be same as when I opened this PR.

**Comment by ShubhankarKG** [comment]
upstream refers to the name you set to remote of your forked repository

**Comment by Dishebh** [comment]
> upstream refers to the name you set to remote of your forked repository

I have set the upstream using `git branch --set-upstream-to <remote-branch>`

**Comment by ShubhankarKG** [comment]
Well, 
1. `git remote add upstream _your-forked-repo-link_`.
2. From next time, `git push upstream _branch-name_`

**Comment by Dishebh** [comment]
@ShubhankarKG my `master` branch (in forked repo) is 10 commits ahead of `CircuitVerse/master` branch while there are `0 files changed with 0 additions and 0 deletions`. I guess that's why the issue arises in the first place. Every time I update my master branch (of forked repo) with the `CircuitVerse/master` branch, it creates a commit in my commit history having the commit message of `Merge pull request #n of CircuitVerse/master`, and that commit message gets reflected in my other branches which are branched out from my `master` branch.

**Pull request closed without merging**
