### PR TITLE
Added pop quiz for Gates page #491

### LINKED ISSUE #491: To add some more new Features
I was thinking we should add on more features for practicing the questions. Such as MCQ's, Short and long questions some Mock test Papers too. 
Most of the colleges take MCQ's test students can practice here.
Adding a mock test feature will lead to enthusiasm among students to practice more.

### PR DESCRIPTION
**Pull request by ritik307**
Added Pop Quiz in the `Gates` page

Fixes #491 (pop quiz/mcq)

#### Changes done:
- [x] MCQ in the gates.md

#### Screenshots
gatesMCQ

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by Shivansh2407 — CHANGES_REQUESTED** [review]
@ritik307 Nice work done 🎉 I would like you to redirect the PR to GSOD 2020 Branch. Rest all looks good to merge with the Updated Book!

**Comment by ritik307** [comment]
@Shivansh2407 Done! I have redirected the PR to the GSoD2020

**Comment by Shivansh2407** [comment]
@ritik307 Please fix the merge conflicts. As you can see that we have a different structure of files in the GSOD 2020 branch, and simply redirecting won't work, you have to create a new PR with the pop quiz implemented in the updated Book, or you can update this PR too!

**Comment by ritik307** [comment]
ok will do it ASAP

**Comment by ritik307** [comment]
@Shivansh2407 Done! I have created a new PR regarding the conflict plz do check it out.

**Pull request closed without merging**
