### PR TITLE
Changed color code of black to correct color code Fixes #591

### LINKED ISSUE #591: Color of code and send button is not visible
## Describe the bug

Color of code and send button is not visible correctly

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/binary-representation/encoding-information.html'
2. Scroll down a little bit
3.  See error

## Screenshots

INITIALLY

image

FINALLY 

image

YES I have solved this issue and i will raise a pr soon

### PR DESCRIPTION
**Pull request by Palaksharma23**
Fixes #591 

All input class with black color were not visible because by mistake color code of black was wrong in the codebase , now i have changed the color code of black to correct color code 

#### Screenshots
INITIALLY 
image

FINALLY
image

#### ✅️ By submitting this PR, I have verified the following

- [yes] Checked to see if a similar PR has already been opened 🤔️
- [yes] Reviewed the contributing guidelines 🔍️
- [yes] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [yes] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Palaksharma23** [comment]
@manjotsidhu can you please once review my pull request and provide me with appropriate feedback .

**Review by manjotsidhu — COMMENTED** [review]
Thanks for contributing, the change looks good and indeed black should be given `#000000` but doing this change, results in some issues.
- Search text color is now black in deploy preview 
image

Check #577 (this black color was introduced in that). 

Can you also make further changes to fix these issues ? You can check [just-the-docs](https://github.com/pmarsceill/just-the-docs) code to check where the $black color is used and make changes accordingly

**Comment by Palaksharma23** [comment]
@manjotsidhu yes sure sir , i will commit the necessary changes asap .

**Comment by manjotsidhu** [comment]
@ayan-biswas0412 Can you review the simulator embeds ?

Also, the embeds on mobile devices overflow the page. This bug is present everywhere and can be dealt separately in #593

**Comment by Palaksharma23** [comment]
Sir can you please once review my last two commits @manjotsidhu 
I have changed the color code accordingly for both

**Comment by Palaksharma23** [comment]
image
image
search dark
code dark

**Review by manjotsidhu — APPROVED** [review]
Apologies for late reply, thanks for your contribution.
Amazing work.

**Pull request merged**
