### PR TITLE
Added Contributor Profile

### LINKED ISSUE #40: Missing contributors profile in README.md
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
The contributors profile can be added to the README page.

### PR DESCRIPTION
**Pull request by fluctix**
Fixes #40 
[GCI Task](https://codein.withgoogle.com/dashboard/task-instances/5903401087401984/)

Screenshots:
screenshot7

### CODE REVIEW

**Comment by fluctix** [comment]
Netlify build fails due to a unrelated reason

**Comment by fluctix** [comment]
@aayush-05 Please review.

**Comment by aayush-05** [comment]
While the initial idea was to have a separate About page, but since we are already having a brief intro in the home page that would make it redundant. I have discussed with the admins and will shortly let you know if this pr is fine or we would need a separate page. @fluctix

**Comment by fluctix** [comment]
Ok......

**Comment by fluctix** [comment]
Closing this as #144 has been merged and now this has conflicts

**Pull request closed without merging**
