### PR TITLE
Added issue and PR templates

### PR DESCRIPTION
**Pull request by nrs1729**
Solves Issue #169

### CODE REVIEW

**Comment by Ananthavijay** [comment]
I think the statements under headers should be made as comment lines

**Comment by nrs1729** [comment]
As in commented out? I think the user needs to see them so they know what to put in each section?

**Comment by nrs1729** [comment]
Yeah I could, it uses bold in the CircuitVerse and Docs templates I think so the styling doesn't continue for the rest of line and comments can be added on the same line without looking like headers

**Comment by YashKumarVerma** [comment]
closing in favor of #272

**Pull request closed without merging**
