### PR TITLE
GSoD2020 Current book contents relocated into the new structure

### PR DESCRIPTION
**Pull request by danielluehr**
The commits in this PR correspond to the relocation of the current contents into the new structure's chapters and sections.

#### Changes done:
- [x] All original content has been incorporated into the new structure
- [x] Relative urls for assets were fixed and replaced by absolute links. They should probably be replaced by `{% link %}` tags
- [x] Some problems were detected in the js of some interactions. Part of it was corrected, but they require further reviewing.

### CODE REVIEW

**Review by Shivansh2407 — APPROVED** [review]
Working Well @danielluehr 🎉 . 
1. There are some links redirecting to learn.circuitverse.org, these will be changed later on section by section right?
2. We can open an issue regarding the alignment of the list in the application1.html and other minor changes.
@satu0king Please review this.

**Comment by satu0king** [comment]
> Relative urls for assets were fixed and replaced by absolute links. They should probably be replaced by {% link %} tags

@danielluehr why was this needed? We should be preferring relative links

**Comment by danielluehr** [comment]
> Working Well @danielluehr tada .
> 
>     1. There are some links redirecting to learn.circuitverse.org, these will be changed later on section by section right?
> 
>     2. We can open an issue regarding the alignment of the list in the application1.html and other minor changes.
>        @satu0king Please review this.

About 1, that is correct, the links will be updated later. They should have been internal links and not "full" urls. The correct way would be:

- `[My page](/path/to/page.html)`
- `[Link to a page]({% link news/index.html %})` (the newest way, it used to be `[Link]({{ site.baseurl }}{% link path/to/file.md %})`)

That way, the links will be independent of the base url.

https://jekyllrb.com/docs/liquid/tags/#links

**Comment by danielluehr** [comment]
> > Relative urls for assets were fixed and replaced by absolute links. They should probably be replaced by {% link %} tags
> 
> @danielluehr why was this needed? We should be preferring relative links. Can you point out to specific files/lines where you changed this.

Everywhere.

Since all assets (js, images and css) are located in the same directory tree `/assets/` it doesn't make sense to have relative urls "upstream" the docs directory tree and into the assets directory tree. It could be ok for objects "downstream" the docs directory tree but, to my understanding, jekyll doesn't recommend that. I guess (I'm not sure, though) it would not copy the assets to the `_site` build directory.

Besides that, having relative url to assets makes it very difficult to track where they are if the content is located at a different level in the `docs/` tree. JTD+jejyll can handle up to three levels in the documentation. If absolute url to assets are used, the same code (md or js) will work in any level. However, if relative urls are used the code has to be modified to match the current depth in the docs directory tree:
- `docs/page.md: "../assets/images/somefile.png"`
- `docs/level1/page.md: "../../assets/images/somefile.png"`
- `docs/level1/level2/page.md: "../../../assets/images/somefile.png"`

with absolute urls to assets it would be just: `"/assets/images/somefile.png"` no matter the position of `page.md`

The only reason I have found to have relative urls pointing to assets would be to "preview" the page in github. However, the site is written to be parsed by jekyll to generate the static site. I don't think the "preview in github" without building it justify its usage.

The same is true for links to pages, see: https://jekyllrb.com/docs/liquid/tags/#links

Please let me know if there is an additional reason which should be considered and would justify going back to relative urls for assets.

**Comment by satu0king** [comment]
> > > Relative urls for assets were fixed and replaced by absolute links. They should probably be replaced by {% link %} tags
> > 
> > 
> > @danielluehr why was this needed? We should be preferring relative links. Can you point out to specific files/lines where you changed this.
> 
> Everywhere.
> 
> Since all assets (js, images and css) are located in the same directory tree `/assets/` it doesn't make sense to have relative urls "upstream" the docs directory tree and into the assets directory tree. It could be ok for objects "downstream" the docs directory tree but, to my understanding, jekyll doesn't recommend that. I guess (I'm not sure, though) it would not copy the assets to the `_site` build directory.
> 
> Besides that, having relative url to assets makes it very difficult to track where they are if the content is located at a different level in the `docs/` tree. JTD+jejyll can handle up to three levels in the documentation. If absolute url to assets are used, the same code (md or js) will work in any level. However, if relative urls are used the code has to be modified to match the current depth in the docs directory tree:
> 
> * `docs/page.md: "../assets/images/somefile.png"`
> * `docs/level1/page.md: "../../assets/images/somefile.png"`
> * `docs/level1/level2/page.md: "../../../assets/images/somefile.png"`
> 
> with absolute urls to assets it would be just: `"/assets/images/somefile.png"` no matter the position of `page.md`
> 
> The only reason I have found to have relative urls pointing to assets would be to "preview" the page in github. However, the site is written to be parsed by jekyll to generate the static site. I don't think the "preview in github" without building it justify its usage.
> 
> The same is true for links to pages, see: https://jekyllrb.com/docs/liquid/tags/#links
> 
> Please let me know if there is an additional reason which should be considered and would justify going back to relative urls for assets.

Ah, thanks for the clarification. You are right, it is better to have absolute URLs.

**Pull request merged**
