### PR TITLE
First PR for GSoD 2020 Interactive Book project

### PR DESCRIPTION
**Pull request by danielluehr**
This is a first (test) PR for the GSoD 2020 Interactive Book project.

It is a "clean" jekyll + jtd + jekyll-spaceship setup. It includes 3 commits:

1. Removal of previous files (.circleci and .github were kept)
1. "Clean" install
1. Empty chapters for new structure

### CODE REVIEW

**Comment by satu0king** [comment]
@Shivansh2407 can you review this?

**Comment by Shivansh2407** [comment]
> @Shivansh2407 can you review this?

Yeah Sure.

**Review by Shivansh2407 — APPROVED** [review]
A glance of all the File Changes with screenshots is attached below:
Light Mode:
Lmodemain
Lmodemainws

Search Light Mode:
search

404 Page:
404l

Dark mode:
Dmodemain
Dmodemainws

Search Dark Mode:
searchd

The Clean Install looks good to me and is working well @danielluehr . This is also working well in the mobile view. The Search Bar and the Side-Bar have a new and improved look and feel . Currently there is only page(/about) as in the screenshots above ( rest all pages have been removed ). The content pages will be added by Daniel in the upcoming PRs.
Great Work @danielluehr . Congratulations on your first PR 🎉 .

**Comment by Shivansh2407** [comment]
The Favicon needs to Be added, Dark Mode Can be Improved but these things can be done on later stages. Let me know your views @satu0king @danielluehr

**Review by satu0king — APPROVED** [review]

**Comment by satu0king** [comment]
@Shivansh2407 , there is no netlify deployment here. Is it confugured only for master branch?

**Pull request merged**
