### PR TITLE
Feature/#505 add quiz raceconditions

### PR DESCRIPTION
**Pull request by ritik307**
Added Pop Quiz in the `docs/seq-design`

Ref #505 

#### Changes done:
- [x] Pop Quiz in `race-conditions.md`

#### Screenshots
racearound

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by manjotsidhu — CHANGES_REQUESTED** [review]
Kindly keep PR neat and tidy by removing unnecessary changes.

**Review by Shivansh2407 — CHANGES_REQUESTED** [review]
As suggested by @manjotsidhu, could you please clean the PR @ritik307 . Rest all looks good to me 👍 . Thank you

**Comment by ritik307** [comment]
@Shivansh2407 Done! Please review

**Comment by manjotsidhu** [comment]
👍 @Shivansh2407 Squash and Merge please

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
