### PR TITLE
[GSoD2020][Fix]:dark mode button on homepage

### LINKED ISSUE #514: [GSoD2020 Branch] Dark Mode Button broken on Home Page
## Describe the bug
"Dark Mode" is broken on Home Page in GSoD2020 branch, fixing this is a priority.

## To Reproduce

Steps to reproduce the behavior -
1.  Go to 'https://betalearn.circuitverse.org'
2.  Click on 'Dark mode'.

## Expected behavior
Dark Mode switch should work as intended, it should change the color scheme to Dark.

**NOTE**: This Dark Mode switch mode just works fine on other pages.

## Desktop:

* OS: Windows 10 Pro 20H2
* Browser: Google Chrome
* Version: 85

---
If anyone would like to work on this, please make sure you are active enough to fix this ASAP.

### PR DESCRIPTION
**Pull request by infern018**
Fixes #514 

#### Changes done:
- [x] Fixed the theme toggle button on the home page

#### Screenshots
image

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by infern018** [comment]
@Shivansh2407  pls review

**Review by manjotsidhu — CHANGES_REQUESTED** [review]
Global scripts are used for all the pages, this dark mode functionality is being run multiple times in pages other than home page. Kindly remove the code from the `general_scripts.html`.

**Comment by infern018** [comment]
> Global scripts are used for all the pages, this dark mode functionality is being run multiple times in pages other than home page. Kindly remove the code from the `general_scripts.html`.

so I should leave the code for theme toggle functionality in `global_scripts.js`?

**Comment by manjotsidhu** [comment]
> > Global scripts are used for all the pages, this dark mode functionality is being run multiple times in pages other than home page. Kindly remove the code from the `general_scripts.html`.
> 
> so I should leave the code for theme toggle functionality in `global_scripts.js`?

Yes

**Comment by infern018** [comment]
@manjotsidhu  pls review!

**Review by manjotsidhu — APPROVED** [review]
Looks good to me, can be merged. @Shivansh2407

**Comment by manjotsidhu** [comment]
@infern018 by the time this get's merged, you can try to fix hound issues in `GSoD2020` branch. Check #460

**Comment by infern018** [comment]
> @infern018 by the time this get's merged, you can try to fix hound issues in `GSoD2020` branch. Check #460

Would love to contribute further, 
Just one doubt :
image
how can I check the hound issues, there is not _details_ option at hound check

**Comment by manjotsidhu** [comment]
> > @infern018 by the time this get's merged, you can try to fix hound issues in `GSoD2020` branch. Check #460
> 
> Would love to contribute further, 
> Just one doubt :
> image
> how can I check the hound issues, there is not _details_ option at hound check

Scroll up and you can see hound reviewed comments.

**Comment by tachyons** [comment]
https://deploy-preview-523--learncircuitverse.netlify.app/ Doesn't work properly

**Comment by manjotsidhu** [comment]
> https://deploy-preview-523--learncircuitverse.netlify.app/ Doesn't work properly

Can you explain further, It's working for me in chrome (also in incognito)

**Comment by infern018** [comment]
> https://deploy-preview-523--learncircuitverse.netlify.app/ Doesn't work properly

Actually on clicking on sidebar nav links its redirecting you to the betalearn site, for instance this : [https://betalearn.circuitverse.org/docs/binary-algebra/](https://betalearn.circuitverse.org/docs/binary-algebra/) , after that the functionality is not working cause we're not in the netlify preview site

**Comment by manjotsidhu** [comment]
> > https://deploy-preview-523--learncircuitverse.netlify.app/ Doesn't work properly
> 
> Actually on clicking on sidebar nav links its redirecting you to the betalearn site, for instance this : https://betalearn.circuitverse.org/docs/binary-algebra/ , after that the functionality is not working cause we're not in the netlify preview site

This issue is a very annoying and I was working on it. This is also the cause Gitpod is not able to work properly.

**Comment by manjotsidhu** [comment]
@tachyons

**Review by Shivansh2407 — APPROVED** [review]
@infern018 Great Work 🎉 . Looks Good to me! @tachyons Please let us know if you're still facing any issue related to dark mode in the Homepage of Interactive Book, else we can merge this PR!!

**Comment by manjotsidhu** [comment]
> @infern018 Great Work 🎉 . Looks Good to me! @tachyons Please let us know if you're still facing any issue related to dark mode in the Homepage of Interactive Book, else we can merge this PR!!

The color scheme fixes for dark mode is addressed in #516

**Pull request merged**
