### PR TITLE
Table of Contents rendered at the bottom of page, fixed //WIP

### PR DESCRIPTION
**Pull request by abhinavsri360**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #
The table of contents in the following pages was rendered at the end of the page. My changes will remove this bug. Further I will add a hardcoded Table of contents for these pages as there are only four and can be done via mentioning them.
Pages: Combinational Logic, MSI Components, Flipflops, and Registers.
Issue can be clearly depicted in the image below::
image
My changes can be seen on the deployment link
Ref #
https://deploy-preview-330--tender-ardinghelli-ebb79f.netlify.app/docs/combinational
https://deploy-preview-330--tender-ardinghelli-ebb79f.netlify.app/docs/flipflop
https://deploy-preview-330--tender-ardinghelli-ebb79f.netlify.app/docs/msi
https://deploy-preview-330--tender-ardinghelli-ebb79f.netlify.app/docs/register

#### Changes done:
Rendering of Table of Contents in the four pages mentioned above was removed.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by abhinavsri360** [comment]
> PR Body incomplete

I was waiting for the checks to complete and add links 😅

**Comment by abhinavsri360** [comment]
@YashKumarVerma PR template completed now. You can review the changes.

**Comment by abhinavsri360** [comment]
I already mentioned in the PR template that I will add hard-coded table of contents for these pages.
The hyperlink which I will create will be linked to other pages for reference.
Sure, I would also like to wait about opinion of others.

**Comment by YashKumarVerma** [comment]
> I already mentioned in the PR template that I will add hard-coded table of contents for these pages which will be present at the top.

will be adding? if so, add WIP to the title.

**Comment by abhinavsri360** [comment]
Okay

**Pull request closed without merging**
