### PR TITLE
Fixed sidebar icon for child pages Closes #236

### LINKED ISSUE #236: Issue with Sidebar button in some pages
- [x] [Interactive Karnaugh Map](https://learn.circuitverse.org/docs/kmapi.html) - Doesn't have a sidebar button. 
- [ ] [Half Adder](https://learn.circuitverse.org/docs/Combinational/half_adder.html) - Doesn't have the icon in sidebar button.

### PR DESCRIPTION
**Pull request by abhinavsri360**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #
There was an issue with the sidebar button in some pages i.e., the button was not uniform across all pages. I have fixed the issue by copying the assets folder in docs directory because I discovered that while the page loaded there were some error logs in the console which expected js libraries to be in the docs folder. So I just made that happen.
Closes #236 
Ref #

#### Changes done:
Fixed sidebar button on the child pages.

#### Screenshots
After Changes
image

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
There is an inactive PR present, for which I asked to work yesterday. Number 237 by Ryuk
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
https://5ec6549c6f31cb0006e28b4f--tender-ardinghelli-ebb79f.netlify.app/
- [x] Tried Squashing the commits into one
All changes are present in the most latest commit.
0f6afb7

### CODE REVIEW

**Comment by abstrekt** [comment]
please create separate PRs for separate concerns

**Comment by abhinavsri360** [comment]
This Pull Request fixes only one issue. No other changes are made.

**Comment by abstrekt** [comment]
Please check commits.

**Comment by abstrekt** [comment]
you're pushing all your commits to this PR, there are 16 commits which deal with different issues, keep master branch untouched & create new branch & PR for each particular issue, as well as please consider rebasing.

**Comment by ShubhankarKG** [comment]
Exactly. Please consider switching branches and checking out from remote master

**Comment by ShubhankarKG** [comment]
> * [x]  Tried Squashing the commits into one
>   All changes are present in the most latest commit.
>   [0f6afb7](https://github.com/CircuitVerse/Interactive-Book/commit/0f6afb7256cde741c890dab7325e4593bf804ebd)

Please don't select the option if not done.

**Comment by abhinavsri360** [comment]
Okay. I will try doing that and push a fresh Request. I tried rebasing but after resolving conflicts caused due to squash and pick I am not able to do anything further.

**Comment by abhinavsri360** [comment]
I think I should switch branches rather than pushing from the master branch all the time.

**Pull request closed without merging**
