### PR TITLE
Fixed rounded rectangles issue in Karnaugh Map in Dark Mode

### LINKED ISSUE #418: Rounded rectangles when using Interactive Karnaugh Map disappear in Dark Mode
## Describe the bug

Rounded rectangles when using Interactive Karnaugh Map disappear in Dark Mode

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/docs/kmapi.html'
2.  Click on 'Dark Mode'
3.  Click on 'Random Example'
4.  See error

## Expected behavior

The rectangles should appear so as to give a better idea about Karnaugh maps

## Screenshots
Screenshot (143)
Screenshot (144)

## Desktop (please complete the following information):

* OS: [Windows]
* Browser [Chrome]

## Additional context
Would like to propose these changes
Screenshot (145)

Screenshot (146)
I am working on it

### PR DESCRIPTION
**Pull request by nileshdas**
Fixed rounded rectangles issue in Karnaugh Map in Dark Mode 

Fixes #418

#### Changes done:
- [x] Changed background of Karnaugh Map SVG
- [x] Changed square numbers(smaller) ones for better visibilty

#### Screenshots
Before:
Screenshot (144)
Screenshot (143)

Now:
Screenshot (146)
Screenshot (145)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by b30wulffz** [comment]
@nileshdas Colors needs to be fixed in Light Mode. Its too much grey.

**Comment by nileshdas** [comment]
@b30wulffz Does this look okay?
Screenshot (151)

Screenshot (150)

**Comment by b30wulffz** [comment]
> @b30wulffz Does this look okay?
> Screenshot (151)
> 
> Screenshot (150)

@nileshdas Better.
@abhinavsri360 @YashKumarVerma Please have a look.

**Comment by nileshdas** [comment]
> The default grey color of the table doesn't look good. Consider changing it please

SVG path are hard coded as black and white and It's the grey colour I think that can accomodate both light and dark mode. If you could suggest any other colour, that'd be great too.

**Comment by nileshdas** [comment]
Deploy preview: https://deploy-preview-419--tender-ardinghelli-ebb79f.netlify.app/docs/kmapi.html
Screenshot (161)
Screenshot (162)
CC: @abhinavsri360 @YashKumarVerma Let me if any other changes are required

**Comment by nileshdas** [comment]
@YashKumarVerma 
Screenshot (163)
Squashed the commits into one and changed the colour
Deploy link: https://deploy-preview-419--tender-ardinghelli-ebb79f.netlify.app/docs/kmapi.html

**Comment by nileshdas** [comment]
Cc: @YashKumarVerma @Shivansh2407

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Pull request merged**
