### PR TITLE
[GCI] Add multiplexer and demultiplexer examples

### LINKED ISSUE #31: Add other variations of MUX and DEMUX
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature - 
Currently, only one variation of multipexer and demultiplexer is shown in the book. Add other variations of the multiplexer and demultiplexer too. The section of the multiplexers and demultiplexers can be divided into sub-section to add the other variations.

### PR DESCRIPTION
**Pull request by junron**
Fixes #31 

Added embeds for 4 : 1 and 8 : 1 multiplexer and demultiplexer.
The embeds do not work in netlify, so no screenshots have been included.

#### 4 : 1
https://circuitverse.org/users/11772/projects/44747
#### 8 : 1
https://circuitverse.org/users/11772/projects/44766
https://circuitverse.org/users/11772/projects/44784
#### 16 : 1
https://circuitverse.org/users/11772/projects/44795
https://circuitverse.org/users/11772/projects/44804

#### 1 : 4
https://circuitverse.org/users/11772/projects/44768
#### 1 : 8
https://circuitverse.org/users/11772/projects/44769
#### 1 : 16
https://circuitverse.org/users/11772/projects/44796

[GCI task](https://codein.withgoogle.com/dashboard/task-instances/5814476373229568/)

### CODE REVIEW

**Comment by sakshi1499** [comment]
I would suggest you add making 16:1 mux with two 8:1 mux or 5 4:1 mux. We want variations in mux and demux so I think that would look better @junron

**Comment by junron** [comment]
Thanks for the feedback, I am working on it!

**Comment by junron** [comment]
@sakshi1499 I made [this](https://circuitverse.org/users/11772/projects/44784) 8 : 1 multiplexer out of 4 : 1 multiplexers. What do you think?

**Comment by junron** [comment]
16 : 1 multiplexer https://circuitverse.org/users/11772/projects/44795

**Comment by junron** [comment]
16 : 1 demultiplexer

**Comment by junron** [comment]
Please review @sakshi1499 @deepak2431

**Comment by sakshi1499** [comment]
That is 1:16 demux and not 16:1 demux

**Comment by sakshi1499** [comment]
That is only in the comment so, I think rest seems good. Add all the links of circuits you have made in the description. I also asked you to make 16:1 using 5 4:1, I think that is missing. Please add these too

**Comment by junron** [comment]
Ah you are right, the comment was a typo. Do you mean the PR description? I'll get the alternative multiplexer done soon.

**Comment by junron** [comment]
@sakshi1499 PR description updated, alternative 16 : 1 multiplexer added

**Comment by deepak2431** [comment]
@junron Looks fine to me. Just make the changes suggested by @sakshi1499

**Comment by sakshi1499** [comment]
@deepak2431 it was your task, I just worked while you were gone. Will you approve it once done?😊

**Comment by sakshi1499** [comment]
@junron In the 16:1 mux, I hope by 0:2 you mean 0,1 select Line and 2:4 is 2,3 select line?

**Comment by sakshi1499** [comment]
I think rest is fine with me😊💯 Good work!

**Comment by deepak2431** [comment]
@sakshi1499 Yeah I would approve his task.
@junron Great work.Thanks!

**Comment by junron** [comment]
@sakshi1499 0:2 refers to the 2 less significant bits, while 2:4 is the 2 more significant bits. This notation was generated when I added a splitter

**Comment by Shivansh2407** [comment]
Please fix the merge conflicts @junron

**Comment by junron** [comment]
Fixed @Shivansh2407

**Pull request merged**
