### PR TITLE
INPUT TEXT IS VISIBLE NOW in DARK-MODE(solve issue #62)

### PR DESCRIPTION
**Pull request by dev9414**
solve the issue of dark mode

### CODE REVIEW

**Comment by aayush-05** [comment]
Hey @dev9414 
I don't think adding inline css is a good way when there is already an external stylesheet in use. It won't make the changes uniform for all the elements on different pages rather just restricts them to a single page.

**Comment by tachyons** [comment]
Improve PR title, remove unrelated changes and add before and after screenshot for both light mode and darkmode

**Comment by aayush-05** [comment]
Hey @dev9414 
Changing the inline css in included html file won't work, because then the same css would be used in the light mode as well. This would break the styling in the light mode.

**Comment by dev9414** [comment]
### **before:**

### dark mode->off
Screenshot (77)

### dark mode->on
Screenshot (78)

### **after:**
### dark mode->off
Screenshot (75)

### dark mode->on
Screenshot (76)

**Comment by dev9414** [comment]
> Improve PR title, remove unrelated changes and add before and after screenshot for both light mode and darkmode

just added screenshot for same !

**Comment by Amansingla97** [comment]
@dev9414  can you resolve the conflicts

**Comment by aayush-05** [comment]
@tachyons @nitin10s can be closed, issue fixed already

**Pull request closed without merging**
