### PR TITLE
Changed 2021 to 2022

### LINKED ISSUE #606: Copyright is not changed to 2022
## Describe the bug
It's not bug, It's just on learn page at footer copyright year is 2021.

## To Reproduce

1.  Go to <a href="https://learn.circuitverse.org/">Learn</a>
2.  At bottom in footer Copyright year is not changed
3.  See error

## Expected behavior
 It should be 2022 I suppose.

## Screenshots
Screenshot 2022-01-16 at 4 02 54 PM

## Desktop (please complete the following information):

* OS: iOS
* Browser: chrome
* Version: 12.0.1

## Smartphone (please complete the following information):

* Device: iPhoneX
* OS: iOS15
* Browser: safari
* Version: 15.1

## Additional context
It should be 2021 only or it should be 2022. Like on official mainpage and other pages it's 2022.

### PR DESCRIPTION
**Pull request by ZaidKhan2002**
Fixes #606 

#### Changes done:
- [x] Changed 2021 to 2022 with JavaScript in all pages.

#### Screenshots
Screenshot 2022-01-18 at 10 48 55 AM

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Comment by ZaidKhan2002** [comment]
I have one doubt. Like I made changes in many files but here there is only one file changed. Is this ok?

**Comment by Palaksharma23** [comment]
@ZaidKhan2002 please add all the changed files in your commit :)

**Comment by ZaidKhan2002** [comment]
> @ZaidKhan2002 please add all the changed files in your commit :)

After making changes I opened my gitpod after timeout and then installed the bundle and jekyll serve all of the changes that I had made got vanished and also tried again same thing happened

**Comment by ZaidKhan2002** [comment]
Also 2nd time after making changes I saw git status it says up to date with my branch working tree clean. Am I going somewhere wrong ?

**Comment by Palaksharma23** [comment]
> Also 2nd time after making changes I saw git status it says up to date with my branch working tree clean. Am I going somewhere wrong ?

checkout to your branch "changedYear" and then make the necessary changes and commit them, make sure to commit only those files in which you have made changes :)
Don't worry if it's your first pull request, everybody face one or two issues initially✌

**Comment by ZaidKhan2002** [comment]
> > Also 2nd time after making changes I saw git status it says up to date with my branch working tree clean. Am I going somewhere wrong ?
> 
> checkout to your branch "changedYear" and then make the necessary changes and commit them, make sure to commit only those files in which you have made changes :) Don't worry if it's your first pull request, everybody face one or two issues initially✌

Thankyou @Palaksharma23. Actually the problem was in my code I was making changes in auto generated html files and was changing year with JavaScript but on slack I got to know that changes will disappear and make change in yml file so made another PR regarding that.

**Pull request closed without merging**
