### PR TITLE
Fixed TOC text design in Boolean Algebra and redesigned search-bar.

### LINKED ISSUE #321: Fix this text of table of content in Boolean Algebra
Boolean Algebra Text :->

Other Page's Text :->

## Are you working on this issue ??
YES, I am.

### PR DESCRIPTION
**Pull request by coding-CEO**
Fixes #321 

Ref #
#### Changes done:
- [x] Fixed text in TOC boolean algebra

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
https://5ec388155bf3d90006e2d023--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by coding-CEO** [comment]
Review @YashKumarVerma @Shivansh2407.

**Comment by coding-CEO** [comment]
> It will be better if you make that 1.1, 1.2 ...... instead of a,b,c,d...

I never touched the a,b,c,d. It is same as it was before.
because, I don't know how to change that.

**Comment by abhinavsri360** [comment]
How did you made it in small case?

**Comment by coding-CEO** [comment]
> How did you made it in small case?

You can check the changes I made in tab of "Files Changed"

**Comment by abhinavsri360** [comment]
Fine in that case.

**Comment by coding-CEO** [comment]
https://5ec3baaa11d7650006d1404f--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html

Scss changes not visible in Netlify.
You may see the search-bar unchanged.

**Comment by coding-CEO** [comment]
@Shivansh2407 merge this PR.

**Comment by YashKumarVerma** [comment]
> @Shivansh2407 merge this PR.

I think 
@Shivansh2407  can you merge this pr or
@Shivansh2407  would you merge this pr 
would have been better

**Comment by coding-CEO** [comment]
@Shivansh2407 Can you merge this PR.

**Comment by coding-CEO** [comment]
> Please update the PR title as per the changes made and issues solved.

Done.

**Comment by Shivansh2407** [comment]
For a nested list, I think these are fine. Let me know your views.

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Pull request merged**
