### PR TITLE
Fixed the Search Input in Boolean Function

### LINKED ISSUE #323: Fix the complete search input field of Boolean Function
In Boolean Function, the top search input has different font, different size.

Boolean Function :->
NPAVScSt (3)

Others :->
NPAVScSt (2)

## Are you working on this issue ??
YES. I am.

### PR DESCRIPTION
**Pull request by coding-CEO**
Gave class to input of truth_table.html which was overriding the input properties of search input.

Fixes #323 

Ref #
## Before:->
NPAVScSt (3)

## After:->
NPAVScSt

#### Changes done:
- [x] Fixed search Input in Boolean Function

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
https://5ec38c9bbb2ffd000730b98c--tender-ardinghelli-ebb79f.netlify.app/docs/bool2.html
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by coding-CEO** [comment]
Review @YashKumarVerma @Shivansh2407 @aayush-05

**Comment by coding-CEO** [comment]
Sorry. It got closed by mistake.

**Comment by abhinavsri360** [comment]
Search-bar is the same even after the changes you made. I see that there is only the change of name rest is the same. Try to change the styling property. Searchbar seems to be extra-long.

**Comment by coding-CEO** [comment]
> Search-bar is the same even after the changes you made. I see that there is only the change of name rest is the same. Try to change the styling property. Searchbar seems to be extra-long.

Search-bar is not same.
1) font family of text inside search bar is changed.
2) height of input inside search bar is changed.
3) length of search-bar was never affected. it is and was the same.

**Comment by abhinavsri360** [comment]
Can you refactor search-bar for all pages and if possible reduce its width by some pixels and increase it's height as it seems to be quite small.

**Comment by coding-CEO** [comment]
> Can you refactor search-bar for all pages and if possible reduce its width by some pixels and increase it's height as it seems to be quite small.

That is a completely different issue.
This issue should not be considered in this PR.

**Comment by abhinavsri360** [comment]
I think you should add these changes along, don't you think that it will look better?

**Comment by coding-CEO** [comment]
> I think you should add these changes along, don't you think that it will look better?

I redesigned the search bar in #322 PR
This should be it.

NPAVScSt

**Comment by coding-CEO** [comment]
@Shivansh2407 merge this PR.

**Comment by YashKumarVerma** [comment]
> @Shivansh2407 merge this PR.

@Shivansh2407  (can you, would you, ...)  merge this PR

**Comment by Shivansh2407** [comment]
Nice Work 👍

**Comment by coding-CEO** [comment]
> > @Shivansh2407 merge this PR.
> 
> @Shivansh2407 (can you, would you, ...) merge this PR

Ok.

**Pull request merged**
