### PR TITLE
Adds SOP, and Conversion from one form to other in Boolean functions page.

### LINKED ISSUE #56: Add POS and SOP
Add following topics after Boolean function-
1. Sum of Product
2. Product of Sum
3. Minimal to Canonical Form Conversion 

Explain with examples, diagrams, flow-charts etc.
 
You are expected to extend the content from here - https://learn.circuitverse.org/docs/bool2.html#sum-of-product-expressions-sop

### PR DESCRIPTION
**Pull request by ShubhankarKG**
Fixes #56 

#### Changes done:
Created new docs for SOP, Standard POS and SOP and Conversion from SOP to POS and minimal to standard forms.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

#### Screenshots of changes

Screenshot from 2020-05-18 12-31-25
Screenshot from 2020-05-18 12-31-35
Screenshot from 2020-05-18 12-31-40
Screenshot from 2020-05-18 12-31-45
Screenshot from 2020-05-18 12-31-53
Screenshot from 2020-05-18 12-31-58

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Deploy preview :- https://5ec233d9e0ca960006fd8799--tender-ardinghelli-ebb79f.netlify.app/
Please review @YashKumarVerma

**Comment by Ananthavijay** [comment]
Compare this one and https://github.com/CircuitVerse/Interactive-Book/pull/190 and merge one

**Comment by ShubhankarKG** [comment]
Please review @Shivansh2407 @YashKumarVerma

**Comment by Shivansh2407** [comment]
@ShubhankarKG Please fix merge conflicts 👍

**Comment by ShubhankarKG** [comment]
Fixed merge conflict in one file

**Comment by ShubhankarKG** [comment]
Please review @Shivansh2407

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Pull request merged**
