### PR TITLE
#285 Redesigned SVG paths for dark mode

### LINKED ISSUE #285: Svg paths are not in accordance with Dark mode
Svg paths are not changing color according to the dark mode.
Which is very bad for user Experiance
as

**Are you working on this ?
Yes, I am working on this issue**

### PR DESCRIPTION
**Pull request by coding-CEO**
Fixes #285 
**Redesigned svg paths for dark mode.**

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)

### CODE REVIEW

**Comment by coding-CEO** [comment]
Please Review.

**Comment by coding-CEO** [comment]
@YashKumarVerma | @mahmodHammad please review.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma | @mahmodHammad please review.

adding preview link to PR

**Comment by coding-CEO** [comment]
> > @YashKumarVerma | @mahmodHammad please review.
> 
> adding preview link to PR

I don't know how to do that...

**Comment by YashKumarVerma** [comment]
> > > @YashKumarVerma | @mahmodHammad please review.
> > 
> > 
> > adding preview link to PR
> 
> I don't know how to do that...

1. click on view more details on netligy
image
2. then click on preview deploy
image

**Comment by coding-CEO** [comment]
> > > > @YashKumarVerma | @mahmodHammad please review.
> > > 
> > > 
> > > adding preview link to PR
> > 
> > 
> > I don't know how to do that...
> 
> 1. click on view more details on netligy
>    image
> 2. then click on preview deploy
>    image

I got this link https://5ebfab8ce0e65e00066e1c2a--tender-ardinghelli-ebb79f.netlify.app/
But my code changes are not there.
Also Notice, when you change the page from sidebar, URL changes...

**Comment by coding-CEO** [comment]
I am not sure why all of the changes are not visible in the netlify link.
https://5ec0eb3966f7490007cf64c4--tender-ardinghelli-ebb79f.netlify.app/docs/fsm_interactive.html

@YashKumarVerma Review

**Comment by YashKumarVerma** [comment]
Can anything be done of the black text as well? they're not visible in dark mode.

**Comment by coding-CEO** [comment]
> Can anything be done of the black text as well? they're not visible in dark mode.

I tried really hard to change the text.
But it is not possible for me.

**Comment by coding-CEO** [comment]
> Can anything be done of the black text as well? they're not visible in dark mode.

It is really hard to differentiate paths, text, circle, etc.
So, that is all what I can do.

You can merge this PR if you want...

**Comment by YashKumarVerma** [comment]
Good work, thanks!

I'd recommend one thing, file an issue for dark text in dark mode if you can. Maybe someone else would like to work on that

**Pull request merged**
