### PR TITLE
Fix sidebar icon for child pages

### LINKED ISSUE #236: Issue with Sidebar button in some pages
- [x] [Interactive Karnaugh Map](https://learn.circuitverse.org/docs/kmapi.html) - Doesn't have a sidebar button. 
- [ ] [Half Adder](https://learn.circuitverse.org/docs/Combinational/half_adder.html) - Doesn't have the icon in sidebar button.

### PR DESCRIPTION
**Pull request by ryuk156**
Fixes #236 

The issue was with every child page generated by Jekyll not able to access the JavaScript files. Fixed that with a if condition to check if the page is a child page or not and changing the url as needed.

Screenshot
image

### CODE REVIEW

**Comment by yash15601** [comment]
@Ananthavijay  @aayush-05 Review Please

**Comment by aayush-05** [comment]
Can you fix the Interactive Karnaugh Map page too, just import the sidebar button code in the kmap layout file as well.

**Comment by yash15601** [comment]
@aayush-05 Done Review

**Comment by yash15601** [comment]
@nitin10s @aayush-05 Review Please

**Comment by yash15601** [comment]
@nitin10s Review please

**Comment by abhinavsri360** [comment]
@Shivansh2407 This PR is inactive as labeled. Can I make same changes and make a Pull Request for the same?

**Comment by Shivansh2407** [comment]
Fixed in #346 . Closing This PR.

**Pull request closed without merging**
