### PR TITLE
Add Asynchronous Ripple Counter

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes: https://github.com/CircuitVerse/Interactive-Book/issues/115
GCI task: https://codein.withgoogle.com/dashboard/task-instances/5893542459736064/

Preview : https://circuitverse.org/users/14228/projects/43064

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@satu0king Please review

**Comment by sakshi1499** [comment]
@Ananthavijay I think we were visioning the interactive circuit that you made to be embedded in the docs file.

**Comment by Ananthavijay** [comment]
@sakshi1499 I don't understand what you are saying

**Comment by VijayAdhithya** [comment]
Let me open a new PR for this since I have deleted my fork without knowing

**Comment by Ananthavijay** [comment]
Let me open a new PR for this since I have deleted my fork without knowing

**Comment by Ananthavijay** [comment]
@sakshi1499 I have moved the PR to: https://github.com/CircuitVerse/Interactive-Book/pull/126

**Pull request closed without merging**
