### PR TITLE
updated docs and images of sequential.md

### PR DESCRIPTION
**Pull request by Dishebh**
--- updated docs and added images of synchronous and asynchronous sequential circuits in sequential.md

## ✅️ By submitting this PR, I have verified the following

* [x] Checked to see if a similar PR has already been opened 🤔️
* [x] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Comment by Dishebh** [comment]
> Work is good,
> 
> kindly update PR Template

Is now fine?

**Comment by YashKumarVerma** [comment]
> > Work is good,
> > kindly update PR Template
> 
> Is it fine now?

remove line -> insert pr title
add checkmark to box

**Comment by Dishebh** [comment]
> Insert description of PR here
> 
> --- updated docs and added images of synchronous and asynchronous sequential circuits in sequential.md
> 
> ##  By submitting this PR, I have verified the following
> * [] Checked to see if a similar PR has already been opened thinking
> * [x]  Reviewed the contributing guidelines mag

Done. Thanks for help

**Comment by YashKumarVerma** [comment]
Good work ! thanks

**Pull request merged**
