### PR TITLE
Added interactive ALU circuit

### LINKED ISSUE #114: ALU interactive Circuit
https://learn.circuitverse.org/docs/alu.html

In addition to the below image, embed an interactive circuit of the same. 

image

### PR DESCRIPTION
**Pull request by JoshHeng**
Added interactive ALU circuit - see below
firefox_3cBEWIHSat

(CircuitVerse circuit link - [https://circuitverse.org/users/14122/projects/42961](https://circuitverse.org/users/14122/projects/42961))

Fixes #114

### CODE REVIEW

**Comment by JoshHeng** [comment]
Updated ALU truth table to properly reflect interactive circuit

**Comment by sakshi1499** [comment]
@satu0king Is this okay? Looks good to me too. I hope interactive circuit here means circuit on CIrcuitVerse platform and not a circuit which changes value when inputs change.

**Comment by JoshHeng** [comment]
@sakshi1499 I believe that the interactive circuit does mean an embedded CircuitVerse circuit like the [Full Adder page](https://learn.circuitverse.org/docs/Combinational/full_adder.html). Because it's embedded users can already change the inputs which will update the output

Please could you complete this task on GCI, thanks

**Comment by sakshi1499** [comment]
I too feel that this is all we need but there are certain parts in the Interactive book where like in flip flop where they have added options to manually enter varied inputs to get outputs. Just waiting for satvik to give a go. @joshheng

**Comment by sal2701** [comment]
@satu0king can you please review this? The circuit is labelled and it can replace the image on the website.

**Comment by sakshi1499** [comment]
I think we should go ahead now? @sal2701 @PragatiVerma18 ? Should we approve it, we have already delayed it?

**Comment by sal2701** [comment]
@sakshi1499 You're right. We should approve it, as it is already delayed. Can you do it?

**Comment by Shivansh2407** [comment]
Please Fix the Failing Checks @JoshHeng 👍

**Comment by JoshHeng** [comment]
@Shivansh2407 @YashKumarVerma Fixed checks, please merge

**Pull request merged**
