### PR TITLE
Created PR and Issue Templates

### PR DESCRIPTION
**Pull request by namantechlabs**
Created PR and Issue Templates for GCI task :)

### CODE REVIEW

**Comment by sakshi1499** [comment]
Looks good @namantechlabs . Should I approve this? @satu0king @aayush-05

**Comment by aayush-05** [comment]
Clear from my side @sakshi1499 . Great work @namantechlabs

**Comment by Parikshit-Hooda** [comment]
LGTM. @aayush-05  @sakshi1499 maybe mark the task as done now.

**Comment by sakshi1499** [comment]
There is just one slight change. I have mentioned it on the GCI Dashboard then will do it. @Parikshit-Hooda 😊

**Comment by Parikshit-Hooda** [comment]
@namantechlabs Maybe add one feature_request template as well in issues

**Comment by namantechlabs** [comment]
@sakshi1499 @Parikshit-Hooda I Have added the feature_request.md file.

**Comment by sakshi1499** [comment]
@namantechlabs greattttt work. @aayush-05 good with you? Should we approve I feel its awesomee?

**Comment by YashKumarVerma** [comment]
done in #170

**Pull request closed without merging**
