### PR TITLE
Added Quiz for latches

### PR DESCRIPTION
**Pull request by ZaidKhan2002**
Fixes #505 

#### Changes done:
- [x] Added pop up quiz for latches.

#### Screenshots
Screenshot 2022-02-01 at 8 25 00 PM

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Review by ayan-biswas0412 — APPROVED** [review]
Good work @ZaidKhan2002 🎉
LGTM @CircuitVerse/issues-team

**Review by vedant-jain03 — APPROVED** [review]
Great work

**Review by pulkit-30 — APPROVED** [review]
Great work @ZaidKhan2002  🎉 
Thanks :D

**Comment by ZaidKhan2002** [comment]
Thank you all! 🙌🏻

**Comment by ayan-biswas0412** [comment]
@manjotsidhu please merge

**Pull request merged**
