### PR TITLE
Fixed the Invisible search text in darkmode

### LINKED ISSUE #246: Search text is not visible in Dark Mode
Screenshot 2020-03-16 at 1 03 56 AM
Screenshot 2020-03-16 at 1 04 15 AM

Solution : Add conditionals and change text color according to mode selected.

I am working on this issue.

### PR DESCRIPTION
**Pull request by coding-CEO**
Changed the colour of text in search bar to White when enters the dark mode.

Fixes #246 

Ref #
LightMode:->
NPAVScSt

DarkMode:->
NPAVScSt (2)

#### Changes done:
- [x] Fixed the colour of text of search bar in dark mode

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by coding-CEO** [comment]
I checked #247 But it changes the background color of search bar to white.
Which is not suitable for dark mode.
That is why I am offering this solution.
Compare and merge whichever fits best.

@YashKumarVerma @aayush-05 @Shivansh2407 .

**Comment by coding-CEO** [comment]
Sample link:
https://5ec37b2fe5f099000757dc1d--tender-ardinghelli-ebb79f.netlify.app/

But as usual, Netlify Don't show scss changes. I don't know why.... :confused:

**Comment by coding-CEO** [comment]
@Shivansh2407 merge this PR.

**Comment by YashKumarVerma** [comment]
> @Shivansh2407 merge this PR.

consider using polite words

**Comment by Shivansh2407** [comment]
> > @Shivansh2407 merge this PR.
> 
> consider using polite words

True 😅 . You can ask for review and then we can review and merge accordingly 👍

**Comment by coding-CEO** [comment]
Sorry.

**Pull request merged**
