### PR TITLE
Make the table generated by "Truth Table Generator" responsive

### LINKED ISSUE #94: Make table generated by "Truth Table Generator" responsive
#### I am submitting a -
* **Bug Report**

#### Describe your bug/feature -
When the number of inputs is large, the table generated by the truth table generator goes out of the page.

#### Current behaviour -
Table goes out of page.

#### Expected behaviour -
Table should be responsive, have a scroll bar.

#### Screenshots (if relevant) -
Screenshot from 2019-11-29 04-32-16

#### Are you working on this issue? (Yes/No)
Nope. For GCI 2019

### PR DESCRIPTION
**Pull request by shotaro27**
I'm Shotaro27. Please review the documents.
スクリーンショット (206)
Resolves #94
Thank you.

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
@shotaro27  please attach the GIFs of 'table responsiveness in action'.
To do this, use a gif making software, focus the gif recorder on the browser and record the table responsiveness when you resize the browser.
Thanks.

**Comment by shotaro27** [comment]
responsive

**Comment by Parikshit-Hooda** [comment]
@shotaro27 I think this is good. 
Thanks!

**Comment by Shivansh2407** [comment]
Nice work @shotaro27

**Pull request merged**
