### PR TITLE
#261 fixed top bar disappearing issue

### PR DESCRIPTION
**Pull request by coding-CEO**
I fixed the issue #261 @YashKumarVerma suggested me in #263  to give a squashed commit. So, I created this new PR to provide the squashed commit.

### CODE REVIEW

**Comment by coding-CEO** [comment]
@YashKumarVerma | @aayush-05 please review this.

**Comment by coding-CEO** [comment]
I made the changes. and solved conflict.

**Comment by coding-CEO** [comment]
> Working Well @coding-CEO  . Please add Screenshots/Screen recording.

Ok. see the screen recording
ezgif com-video-to-gif

**Comment by YashKumarVerma** [comment]
good work !

**Comment by coding-CEO** [comment]
> good work !

Thanks.

**Pull request merged**
