### PR TITLE
Enabled scroll in the search bar

### PR DESCRIPTION
**Pull request by shubhdeep123**
Fix Scroll Issue in search bar

Fixes # fixed the scroll issue of search bar till 5 searches.

#### Changes done:
- [x] Task 1

#### Screenshots
after
before

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by shubhdeep123** [comment]
@Shivansh2407 @YashKumarVerma please have a look at this pull request fixing issue #447

**Review by Shivansh2407 — CHANGES_REQUESTED** [review]
Nice Work @shubhdeep123 👍 . A suggestion would be that can you align the dropdown with the search bar along with fixing the width of the dropdown (Make the width equal to that of the search bar).
After these changes, we will be ready to merge this PR.

**Comment by shubhdeep123** [comment]
@Shivansh2407 sure even I was thinking of the same I ll do the same soon

**Comment by shubhdeep123** [comment]
@Shivansh2407 have a look is this good now?

**Comment by shubhdeep123** [comment]
Screenshot from 2020-09-01 23-31-26
@Shivansh2407 please have a look i have made it responsive too.

**Comment by shubhdeep123** [comment]
Screenshot from 2020-09-02 10-30-16
Screenshot from 2020-09-02 10-30-29
Screenshot from 2020-09-02 10-30-37
@Shivansh2407  now it's responsive for mobile too. You can review it now and if there any changes that can be made please let me know.

**Review by Shivansh2407 — APPROVED** [review]
Awesome Work @shubhdeep123 🎉 . Keep Contributing .
Will be opening another issue for an existing unsolved bug in the search bar that is actually when the number of elements in the drop down are less(1-2), the drop down should not be fixed to its length, it should rather be dynamic while changing the length up to some specific rows of results.
Please see the image for more clear idea. This white space does not provide a good user experience.
image

**Comment by shubhdeep123** [comment]
@Shivansh2407 sure further I will work on it.

**Pull request merged**
