### PR TITLE
Added different types of Synchronous and Asynchronous Counters

### PR DESCRIPTION
**Pull request by Ananthavijay**
GCI task : https://codein.withgoogle.com/dashboard/task-instances/6562341051695104/
 
Preview: https://hardcore-hoover-332f7d.netlify.com/docs/counter.html

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@sakshi1499 Have a look

**Comment by sakshi1499** [comment]
Are the images made by you? Please make sure they are made by you. I have seen the images, they look good. Content seems good too. Please add screenshot along with the preview in the description.

**Comment by sakshi1499** [comment]
I haven't used netlify, why is it failing? @Ananthavijay

**Comment by Ananthavijay** [comment]
@sakshi1499 the images are made by me. 
I also don't know why netlify fails 😫

**Comment by sakshi1499** [comment]
@tachyons can you please see and tell why Netlify is failing?

**Comment by Ananthavijay** [comment]
@sakshi1499 I will try to find a solution for it

**Comment by sakshi1499** [comment]
Please do, I'll check too 🙄

**Comment by Ananthavijay** [comment]
@sakshi1499 My branch is not updated that's why netlify fails.
Let me open a new PR for this

**Comment by Ananthavijay** [comment]
moved PR to : https://github.com/CircuitVerse/Interactive-Book/pull/139

**Pull request closed without merging**
