### PR TITLE
Fixed indentation of Algebraic Simplification for better readability

### PR DESCRIPTION
**Pull request by Dishebh**
#### Changes done:
- [x] Fixed indentation of `Algebraic Simplification` for better readability

#### Screenshots
Screenshot from 2020-05-21 23-28-37

Preview Link: https://deploy-preview-342--tender-ardinghelli-ebb79f.netlify.app/docs/bool2.html

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Dishebh** [comment]
> It would be better if you write laws used instead of comments present on the page.

Done. Thanks!

**Comment by abhinavsri360** [comment]
You added laws only for two lines. How about other lines.

**Comment by Dishebh** [comment]
Added Laws and reduced steps @abhinavsri360 @Shivansh2407

**Comment by Dishebh** [comment]
@abhinavsri360 Pls refer this link https://www.electronics-tutorials.ws/boolean/bool_6.html

**Comment by abhinavsri360** [comment]
https://en.m.wikipedia.org/wiki/Absorption_law
There are six laws which can be applied on AND and OR gate. Also, laws are not further divided into anything such as OR xyz law or AND xyz law.

**Comment by Dishebh** [comment]
> https://en.m.wikipedia.org/wiki/Absorption_law
> There are six laws which can be applied on AND and OR gate. Also, laws are not further divided into anything such as OR xyz law or AND xyz law.

I am not really sure, I have seen many others actually bifurcating the laws into its sub parts. Anyways, I will make the changes. Thanks for your feedback!

**Comment by Dishebh** [comment]
Done

**Comment by abhinavsri360** [comment]
> > https://en.m.wikipedia.org/wiki/Absorption_law
> > There are six laws which can be applied on AND and OR gate. Also, laws are not further divided into anything such as OR xyz law or AND xyz law.
> 
> I am not really sure, I have seen many others actually bifurcating the laws into its sub parts. Anyways, I will make the changes. Thanks for your feedback!

We should refer to George Boole. Initially he published only 6 Laws and they are not bifurcated further.

**Comment by Dishebh** [comment]
> Where did the term 'CD' went? Please solve the expression correctly

Absorption Law applied on CD + D (mentioned in comments), reduced it to D.

**Comment by Dishebh** [comment]
@Shivansh2407 @Shivansh2407 @YashKumarVerma pls review.

**Comment by abhinavsri360** [comment]
Just add one more step which portrays and minimizes CD + D then it will be fine

**Comment by Dishebh** [comment]
@abhinavsri360 I hope this does the work

**Comment by abhinavsri360** [comment]
Looks good to me, wait for it to be reviewed by others.

**Pull request merged**
