### PR TITLE
Added open with gitpod option in readme.

### PR DESCRIPTION
**Pull request by PragatiVerma18**
fixes #81

### CODE REVIEW

**Comment by tachyons** [comment]
I am getting this error

`bash: /var/gitpod/docker_env: No such file or directory`

**Comment by PragatiVerma18** [comment]
Try now...I have updated the code of docker file.

**Comment by tachyons** [comment]
Still not working 

```
building base image

initializing base image context
UGit operations complete                       location=/workspace/init
running base image build
Step 1/4 : FROM gitpod/workspace-full
latest: Pulling from gitpod/workspace-full
Digest: sha256:5404ba92971a07c06855aa697a9cc490d190a110eab94c386c72f7ae20e53603
Status: Image is up to date for gitpod/workspace-full:latest
 ---> feeb5821a80f
Step 2/4 : USER gitpod
 ---> Running in 8f97f40bb3e2
 ---> 922a946f7380
Step 3/4 : RUN /home/gitpod/.rvm/bin/rvm install "ruby-2.5.1" &&     /home/gitpod/.rvm/rubies/ruby-2.5.1/bin/gem install jekyll bundler
 ---> Running in 7c91cd51378a
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/19.04/x86_64/ruby-2.5.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system.....
Installing required packages: gawk, bison, sqlite3.......
Error running 'requirements_debian_libs_install gawk bison sqlite3',
please read /home/gitpod/.rvm/log/1574150501_ruby-2.5.1/package_install_gawk_bison_sqlite3.log
Requirements installation failed with status: 100.



build failed: cannot build base image: The command '/bin/sh -c /home/gitpod/.rvm/bin/rvm install "ruby-2.5.1" &&     /home/gitpod/.rvm/rubies/ruby-2.5.1/bin/gem install jekyll bundler' returned a non-zero code: 100

Error: build failed: cannot build base image: The command '/bin/sh -c /home/gitpod/.rvm/bin/rvm install "ruby-2.5.1" &&     /home/gitpod/.rvm/rubies/ruby-2.5.1/bin/gem install jekyll bundler' returned a non-zero code: 100
```

**Comment by tachyons** [comment]
https://gitpod.io/#https://github.com/CircuitVerse/Interactive-Book/pull/84/files

**Pull request closed without merging**
