### PR TITLE
Recreate And/Or/Xor tool

### LINKED ISSUE #433: Redesigning of and/or/xor tool in binary2.html
## Is your feature request related to a problem? Please describe.

Previous and/or/xor tool has issues while using on mobile i.e. it is not available for mobile. Plus it does not match with the UI of the webpage.
This is how it looks right now:
image

## Describe the solution you'd like

I previously worked on binary to decimal convertor in binary.html which looks like this: 
image
Hence I decided to follow a similar layout while redesigning this tool so that it perfectly fits the UI and is responsive on different screen sizes.

## Describe alternatives you've considered

.None

## Additional context

Here is a rough design of the same that I am going to implement:
and/or/xor tool
Feedback for new design welcomed.

### PR DESCRIPTION
**Pull request by b30wulffz**
Finally completed the and/or/xor tool which is following a new UI and is fully responsive.
Any changes are welcomed.
PS: Did some minor changes in B2D tool (binary.html #417 ) and pushed with this PR although it is not related to this issue.

Fixes #433 

#### Changes done:
- [x] Recreated and/or/xor tool from scratch

#### Screenshots
video

Light UI:
lightUi1

Dark UI:
darkUi1

Mobile View:
mobile1

#### Preview Link(s): 
[https://deploy-preview-437--tender-ardinghelli-ebb79f.netlify.app/docs/binary2.html](https://deploy-preview-437--tender-ardinghelli-ebb79f.netlify.app/docs/binary2.html)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by b30wulffz** [comment]
@Shivansh2407 @YashKumarVerma @abhinavsri360 Please review 😄

**Comment by b30wulffz** [comment]
@abhinavsri360 Thanks for the feedback. I completely agree with the point i.e. we can use some vector icons with options(along with text). But keeping the logo between two numbers might cause a little bit of redundancy. Plus UI might look little uneven, well that can be fixed. 
What do other everyone else think?

**Comment by b30wulffz** [comment]
@abhinavsri360 Well I added the element, without effecting UI.

gif

Elements moved a little up and down. Is this better or should I modify?

**Comment by b30wulffz** [comment]
Will squash all commits once all changes are done!

**Comment by b30wulffz** [comment]
@mahmodHammad Thank you 😄

**Comment by b30wulffz** [comment]
Changes Done + Some minor fixes
image
😄

**Comment by Shivansh2407** [comment]
Just Squash these commits and this PR will be ready to merge 👍 .

**Comment by b30wulffz** [comment]
Consider @abhinavsri360's feedback, is there any need to add vector icons? 
I feel that this is looking better without them.

**Comment by Shivansh2407** [comment]
> Consider @abhinavsri360's feedback, is there any need to add vector icons?
> I feel that this is looking better without them.

Can you post a Screenshot with the Icons ?

**Comment by b30wulffz** [comment]
image

**Comment by Shivansh2407** [comment]
How About adding small icons of gates instead of the symbols? Can you try that and post a screenshot? Please let me know your views

**Comment by b30wulffz** [comment]
Keeping text and image side by side is not looking good. Hence I decided to remover text. Or I can edit image and put text inside the gate?
image

Image Credits:
https://thenounproject.com/term/logic-gates-or/411962/
https://thenounproject.com/term/logic-gates-and/411961/
https://thenounproject.com/term/logic-gates-xor/411965/

**Comment by Shivansh2407** [comment]
How about using the gates that are used in the website itself. These have text written inside the gates.
image
I guess this will look much more better.

**Comment by b30wulffz** [comment]
These images are not of equal proportion. + Background needs to be removed.
(Not a big task, but require editing)
Newly added images look better, text can be inserted in between, if you want.

**Comment by Shivansh2407** [comment]
> These images are not of equal proportion. + Background needs to be removed.
> (Not a big task, but require editing)
> Newly added images look better, text can be inserted in between, if you want.

Cool @b30wulffz, Go ahead and Edit the Newly added images. Add appropriate text Between them and Post a screenshot when its done.

**Comment by b30wulffz** [comment]
A small doubt, Won't there be any problem with copyright?

**Comment by b30wulffz** [comment]
Looks little small though
image

**Comment by Shivansh2407** [comment]
Looks Good 👍 . Please push the changes so that we can continue to merge this.
As far as Copyright is concerned, Have a look at this : https://thenounproject.zendesk.com/hc/en-us/articles/203605383-Can-I-trademark-an-icon-to-use-for-my-business-logo-

and the image below : 
image

**Comment by b30wulffz** [comment]
Yeah, its < 100px.

**Comment by b30wulffz** [comment]
Squashed :)

**Comment by YashKumarVerma** [comment]
@Shivansh2407  time to get it live :heart:

**Comment by b30wulffz** [comment]
Its live 🥰
Thank you so much.

**Comment by Shivansh2407** [comment]
It is really looking awesome @b30wulffz . Keep Contributing 👍😇

**Comment by b30wulffz** [comment]
There is a small bug. If the website is cached in the browser, it is not loading the updated javascript file. Hence one needs to do a forced refresh by pressing ```ctrl+f5```

For more details: [https://superuser.com/questions/36106/force-refreshing-only-javascript-files-in-firefox-and-chrome](https://superuser.com/questions/36106/force-refreshing-only-javascript-files-in-firefox-and-chrome)

**Comment by abhinavsri360** [comment]
@b30wulffz changes you made were <3

**Pull request merged**
