### PR TITLE
Added info of Master Slave JK Flip-flop 

### PR DESCRIPTION
**Pull request by Ananthavijay**
[GCI Task](https://codein.withgoogle.com/dashboard/task-instances/6008223807569920/)
Fixes https://github.com/CircuitVerse/Interactive-Book/issues/30

- All the images were drawn in draw.io
- Added information regarding Master Slave JK Flip-flop.
- https://circuitverse.org/simulator/embed/47630
- https://deploy-preview-217--tender-ardinghelli-ebb79f.netlify.com/docs/flipflop/masterslave_jk_flipflop.html

### Screenshots
Screenshot (207)
Screenshot (208)
Screenshot (209)
Screenshot (210)
Screenshot (211)

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Please review @aayush-05 . There are issues with the sidebar in all the subpages ( eg: T flip-flop) which was present already

**Comment by aayush-05** [comment]
The sidebar seems to work fine both in my local server and the deployed version. Please check if you are running the latest master.
image

**Comment by Ananthavijay** [comment]
@aayush-05 I was talking about this one

This screenshot was added by ericsheng in his PR
See near the sidebar button
What should I do? Submit my task for approval?

**Comment by Ananthavijay** [comment]
@aayush-05 I have also fixed the issue which I have pointed out before.
There was also another issue with the breadcrumb-nav.
Check out the preview below for more info
### Before:
SR Flip-Flop - CircuitVerse (1)
### After:
SR Flip-Flop - CircuitVerse

**Comment by Ananthavijay** [comment]
Please review @aayush-05 , Thanks

**Comment by ericsheng495** [comment]
Yes, I agree with @Ananthavijay, I think @aayush-05 you only fixed the issue in your local environment and didn't push it to the circuit verse interactive book. I took a look at the original interactive book and it looks like this:

Screen Shot 2020-01-21 at 7 36 47 AM

**Comment by Ananthavijay** [comment]
@ericsheng495 I did not explain the issue properly at first.

**Comment by aayush-05** [comment]
@Ananthavijay please confirm are you talking about the overlapping of the Sidebar button with the bread crumb navigation ? And the fact that due to this sometimes you get redirected to another page in  the breadcrumb trail rather than getting the Sidebar switched ?

**Comment by Ananthavijay** [comment]
Yep @aayush-05 I am talking about the overlapping of Sidebar button with the bread crumb navigation, and I guess now I have fixed it

**Comment by aayush-05** [comment]
Okay @Ananthavijay, looks good to me. Just mention the change regarding the breadcrumb in the pr title as well.
This can be merged @tachyons

**Comment by Ananthavijay** [comment]
I will remove the commits regarding breadcrumb nav since it has already been done on another PR

**Comment by aayush-05** [comment]
Good to be merged @tachyons

**Pull request merged**
