### PR TITLE
[GCI] #43 Added types of Asynchronous and Synchronous counter

### LINKED ISSUE #43: Add types of Asynchronous and Synchronous counter
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
The types of asynchronous and synchronous is missing in the book which should be added.

### PR DESCRIPTION
**Pull request by JyothsnaAshok**
Fixes #43 Add types of Asynchronous and Synchronous counter 

### Description
I've added the types of Asynchronous and Synchronous counters.

### Screenshots of changes(if any)
ss1

ss2

ss3

GCI Task Instance: https://codein.withgoogle.com/dashboard/task-instances/4910126952087552/

### CODE REVIEW

**Comment by sakshi1499** [comment]
Asynchronous counters are of mainly four types:
2 bit ripple up counter with +ve edge
2bit ripple up counter with -ve edge
2 bit ripple down counter with +ve edge
2 bit ripple down counter with -ve edge
Add a little description about each of these counters

Synchronous counters are of multiple types so you could mention any 3/4

**Comment by JyothsnaAshok** [comment]
Okay I'll do that.

**Comment by deepak2431** [comment]
@sakshi1499 What do think of addition of logical diagram for each type?

**Comment by sakshi1499** [comment]
@deepak2431 are you referring to the ripple pulse diagram? Or the JK flip flop one?

**Comment by deepak2431** [comment]
@sakshi1499 Ripple pulse diagram would be fine I think.

**Comment by sakshi1499** [comment]
@jyothsnaAshok the description is much better now. Good work on that. Please add proper screenshots in the description.

**Comment by sakshi1499** [comment]
Okay then. Please add ripple pulse diagram also for asynchronous. Synchronous will have flip flop diagram most probably. So add that too

**Comment by deepak2431** [comment]
@sakshi1499 Yeah, hat would make it more informative.

**Comment by sakshi1499** [comment]
@JyothsnaAshok Looks good. @deepak2431 Are we good to go? @tachyons Please review this once.

**Comment by deepak2431** [comment]
@JyothsnaAshok You have done a great job. Only one suggestion after displaying the images it doesn't looks clean to me as all images have different width and height and please add some newline too. What  do you think @sakshi1499 
Thanks!

**Comment by tachyons** [comment]
Are the attached images drawn by you? If not are they free to use? Do they require attribution ?

**Comment by JyothsnaAshok** [comment]
@tachyons I've made a new pull request at #112 . The images are drawn by me, so they won't need attribution. @sakshi1499 @deepak2431

**Pull request closed without merging**
