### PR TITLE
added pop quiz in negative-quantities.md page

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #505

#### Changes done:
- [x] Added pop quiz in ```docs/binary-representation/negative-quantities.md```

#### Screenshots
image

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@Shivansh2407 can you please review it ? also see the issue with proper instruction I have written to refrain from rework in this topic [here](https://github.com/CircuitVerse/Interactive-Book/issues/505)

**Review by Shivansh2407 — CHANGES_REQUESTED** [review]
Working Well @ayan-biswas0412 🎉 I would like you to fix a minor thing here, the '?' enters a new line which looks weird in some questions ( It is fixed when the sidebar is collapsed but it again occurs when the sidebar is opened ) .

**Comment by ayan-biswas0412** [comment]
@Shivansh2407 now I have fixed the problem
image

**Review by Shivansh2407 — APPROVED** [review]
🎉

**Pull request merged**
