### PR TITLE
Added Content in number-bases.md Fixes Fixes #596

### LINKED ISSUE #596: No content in Number-bases.md file
## Describe the bug

Currently there is no content in Number bases 

## To Reproduce

https://learn.circuitverse.org/docs/binary-representation/number-bases.html

### PR DESCRIPTION
**Pull request by Palaksharma23**
Fixes #596

A meaningful title for PR, not like: made changes to xyz.md

Fixes #596

#### Changes done:
- [x] Task 1 I have added content in number-bases.md file for Number Bases section in Binary Representation.

with a screenshot showing the comparison between old and new -->
#### Screenshots

**INITIALLY**
image

#### ✅️ By submitting this PR, I have verified the following

- [yes] Checked to see if a similar PR has already been opened 🤔️
- [yes] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Comment by Palaksharma23** [comment]
@manjotsidhu sir can you please once review my pull request .

**Review by manjotsidhu — CHANGES_REQUESTED** [review]
image

These sub-headings are not distinguishable among other list items. It would be better not to make them part of list and rather have `###` (h3) headings for it.

**Comment by manjotsidhu** [comment]
QC @Shivansh2407 @ayan-biswas0412

**Review by ayan-biswas0412 — APPROVED** [review]
Good work @Palaksharma23 🎉

**Comment by Palaksharma23** [comment]
image

**Comment by Palaksharma23** [comment]
done sir :) @manjotsidhu

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
there are some grammatical suggestions given by the bot, please review them once @Palaksharma23

**Comment by Palaksharma23** [comment]
done sir :) @ayan-biswas0412

**Review by manjotsidhu — CHANGES_REQUESTED** [review]
```Check warning on line 25 in docs/binary-representation/number-bases.md

GitHub Actions
/ Language check
docs/binary-representation/number-bases.md#L25
[LanguageTool] reported by reviewdog 🐶
Use a comma before ‘so’ if it connects two independent clauses (unless they are closely connected and short). (COMMA_COMPOUND_SENTENCE_2[6])
Suggestions: `, so`
Rule: https://community.languagetool.org/rule/show/COMMA_COMPOUND_SENTENCE_2?lang=en-US&subId=6
Category: PUNCTUATION

Raw Output:
docs/binary-representation/number-bases.md:25:120: Use a comma before ‘so’ if it connects two independent clauses (unless they are closely connected and short). (COMMA_COMPOUND_SENTENCE_2[6])
 Suggestions: `, so`
 Rule: https://community.languagetool.org/rule/show/COMMA_COMPOUND_SENTENCE_2?lang=en-US&subId=6
 Category: PUNCTUATION
```
ref: https://github.com/CircuitVerse/Interactive-Book/runs/4761081428?check_suite_focus=true

**Review by manjotsidhu — APPROVED** [review]
LGTM 🔥 

In future it will be really useful if we also have calculator to convert different number bases along with the steps.

**Pull request merged**
