### PR TITLE
Made commutative and associative law examples look good on mobile

### LINKED ISSUE #294: Too much extra space in the examples of Commutative and associative law
There is too much extra space in the examples of Commutative and associative law which make one of the two examples kinda invisible in the mobile view. A solution could be that examples can be presented in different lines.
Please look into this.
@YashKumarVerma @Dishebh

_Originally posted by @abhinavsri360 in https://github.com/CircuitVerse/Interactive-Book/pull/288#issuecomment-629602633_

### PR DESCRIPTION
**Pull request by coding-CEO**
Fixes #294 

## Before:->
a

## After:->
b

#### Changes done:
- [x] changed the design of commutative and associative law examples. so that they will look good on mobile.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by coding-CEO** [comment]
Please Review @YashKumarVerma .

**Comment by YashKumarVerma** [comment]
> Please Review @YashKumarVerma .

sample link ?

**Comment by abhinavsri360** [comment]
I think numbers 1&2 can be omitted as there are just two examples, also the term 'examples' and the examples 1&2 should be in different lines. Thus will look clean in my opinion. Please look into this @coding-CEO

**Comment by coding-CEO** [comment]
> I think numbers 1&2 can be omitted as there are just two examples, also the term 'examples' and the examples 1&2 should be in different lines. This will look clean in my opinion. Please look into this @coding-CEO

a

How about this @abhinavsri360 ?

**Comment by coding-CEO** [comment]
> > Please Review @YashKumarVerma .
> 
> sample link ?

https://5ec0b8264d9fda00069927b2--tender-ardinghelli-ebb79f.netlify.app/

This is sample link of original solution. @YashKumarVerma .

**Comment by abhinavsri360** [comment]
Yeah looks more clean, you might do the same for other examples.

**Comment by coding-CEO** [comment]
> Yeah looks more clean, you might do the same for other examples.

ok

**Comment by coding-CEO** [comment]
> > Please Review @YashKumarVerma .
> 
> sample link ?

https://5ec0dc7e589d3f000773b945--tender-ardinghelli-ebb79f.netlify.app/

Latest change link. @YashKumarVerma @abhinavsri360 .

**Comment by abhinavsri360** [comment]
I don't think it's working to what you did. Try opening the link on mobile. All examples in AND gate are prefixed with the number '1' and issue seems not to be resolved. Please look into this closely @coding-CEO

**Comment by coding-CEO** [comment]
> I don't think it's working to what you did. Try opening the link on mobile. All examples in AND gate are prefixed with the number '1' and issue seems not to be resolved. Please look into this closely @coding-CEO

Sorry, Actually the link was Wrong.
Checkout this.
https://5ec0dc7e589d3f000773b945--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html

**Comment by abhinavsri360** [comment]
Just remove remove the extra line after the example of Distributive line then it will be fine to me.

**Comment by coding-CEO** [comment]
> Just remove remove the extra line after the example of Distributive Law then it will be fine to me.

Done.

**Comment by coding-CEO** [comment]
Most Latest Link.
https://5ec0e7b5a498970006934e5b--tender-ardinghelli-ebb79f.netlify.app/docs/bool.html

Review @YashKumarVerma | @abhinavsri360

**Comment by abhinavsri360** [comment]
Looks good to me. Wait for it to be reviewed by Yash.

**Comment by coding-CEO** [comment]
Sure.

**Comment by coding-CEO** [comment]
@YashKumarVerma plese review.

**Comment by coding-CEO** [comment]
@YashKumarVerma waiting for review

**Comment by YashKumarVerma** [comment]
Good work !

**Pull request merged**
