### PR TITLE
feat: page progress bar

### LINKED ISSUE #578: feat: Progress Bar for Documentation Page
## Is your feature request related to a problem? Please describe.

Progress Bar for Documentation Page will let user know the progress he/she made while reading at the top.

## Describe the solution you'd like

Using JS and pageoffset methods

### PR DESCRIPTION
**Pull request by vedant-jain03**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #578 

Ref #

#### Changes done:
- [x] Task 1

#### Screenshots

https://user-images.githubusercontent.com/76901313/139542748-7a1f6824-942b-4dda-9105-18b00a84003c.mp4

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@manjotsidhu @nitin10s

**Review by manjotsidhu — APPROVED** [review]
Code looks good, is it responsive for mobile devices ?

**Comment by vedant-jain03** [comment]
> Code looks good, is it responsive for mobile devices ?

Yes @manjotsidhu It is responsive for mobile as well, have a look: 

https://user-images.githubusercontent.com/76901313/142552862-bc9c0c4f-16b8-48cb-a507-ffdb2b5db6d8.mp4

**Comment by vedant-jain03** [comment]
> Nice work @vedant-jain03 🎉

Thankyou @Shivansh2407 😄

**Pull request merged**
