### PR TITLE
Elaborated flip-flop interaction

### PR DESCRIPTION
**Pull request by Ananthavijay**
[GCI TASK](https://codein.withgoogle.com/dashboard/task-instances/6474297686622208/)
Fixes https://github.com/CircuitVerse/Interactive-Book/issues/55

- Elaborated flip-flop interaction in a way that even a beginner could understand it. 
- https://deploy-preview-221--tender-ardinghelli-ebb79f.netlify.com/docs/flipflop2.html

#### JK flip-flop:

Screenshot (213)

#### RS flip-flop:

Screenshot (215)

#### D flip-flop:

Screenshot (216)

#### T flip-flop:

Screenshot (217)

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Please review @sakshi1499

**Comment by sakshi1499** [comment]
In JK flip flop jist state that in case of 1 and 1 the next state is the compliment of the existing state. Same in the case of T. I hope the way you have written it, it is not copied from somewhere, please confirm that too

**Comment by Ananthavijay** [comment]
I have not copied it. And what you have said is already written over there @sakshi1499

**Comment by Ananthavijay** [comment]
See the second point in T flip-flop as well as JK flip-flop

**Comment by sakshi1499** [comment]
I want you to remove the word toggle in JK. Mainly SR flip flop toggles. JK was introduced to overcome that so that is what I mentioned

**Comment by Ananthavijay** [comment]
Done! @sakshi1499

**Comment by sakshi1499** [comment]
Good workkk!

**Comment by aayush-05** [comment]
Good to be merged @tachyons

**Pull request merged**
