### PR TITLE
Add Asynchronous Ripple Counter

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes: #115
GCI task: https://codein.withgoogle.com/dashboard/task-instances/5893542459736064/

Preview: https://circuitverse.org/users/14228/projects/43064

Screenshot :  

Screenshot (102)

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@satu0king @sakshi1499 Pls Review

**Comment by sakshi1499** [comment]
Please add a screenshot of how it looks

**Comment by Ananthavijay** [comment]
Ok mam

**Comment by VijayAdhithya** [comment]
Screenshot (102)

**Comment by Ananthavijay** [comment]
Screenshot (102)

**Comment by Ananthavijay** [comment]
@sakshi1499 Added

**Comment by sakshi1499** [comment]
@PragatiVerma18 @eKuG Looks good to me. What about you guys? @satu0king should we go ahead and approve this?

**Comment by eKuG** [comment]
Awesome. I think we should approve this task

**Comment by sakshi1499** [comment]
@sal2701 Please review once?

**Comment by Ananthavijay** [comment]
Done. Updated  @sal2701 
Have a look at it here : https://pensive-booth-aeab0e.netlify.com/docs/counter.html

**Comment by Ananthavijay** [comment]
@sal2701 no issues man.. I wil make it within 10min

**Comment by Ananthavijay** [comment]
@sal2701 I have made it

**Comment by aayush-05** [comment]
@Ananthavijay if possible can you reopen it ? 
@tachyons it will be good to merge then

**Comment by Ananthavijay** [comment]
I will open a new PR

**Comment by Ananthavijay** [comment]
@aayush-05 I have moved this PR to https://github.com/CircuitVerse/Interactive-Book/pull/267

**Pull request closed without merging**
