### PR TITLE
#242 fixing alignment issue  at operator section

### PR DESCRIPTION
**Pull request by mahmodHammad**
### Old :
image

### New

image

#### this issue at this page : https://learn.circuitverse.org/docs/binary2.html

### CODE REVIEW

**Comment by mahmodHammad** [comment]
@Ananthavijay @aayush-05 
review please !

**Comment by tachyons** [comment]
Do not make changes in _site folder, it is for statically generated content

**Comment by mahmodHammad** [comment]
> Do not make changes in _site folder, it is for statically generated content
@tachyons 
This is the only way to fix this issue - if there's is any method to fix this issue let me know please

**Comment by mahmodHammad** [comment]
@tachyons the issue is at that statically generated content.
Could you please recommend any other solution to fix it?

**Comment by aayush-05** [comment]
@mahmodHammad every content in the statically generated file is coming from the already written static files at server. Try looking at _includes/binary2.html ; it has the styles for this portion.

**Comment by coding-CEO** [comment]
I fixed this issue in #262 
Please Review it.

**Comment by aayush-05** [comment]
@mahmodHammad are you still working on this ?

**Comment by mahmodHammad** [comment]
@aayush-05
I already did the job.
The problem were on the static files, thats why i had to change it.
I have no idea why this could not be merged.

**Comment by mahmodHammad** [comment]
If you can do it without changing the static files... Go ahead

**Comment by mahmodHammad** [comment]
@aayush-05 i think @coding-CEO did that for me,
so we can close this

**Pull request closed without merging**
