### PR TITLE
Removed unnecessary files in _layout folder

### LINKED ISSUE #295: layout /about, /page, /post, /home  all have same content
So, I did a quick lookup and realized that the kmap.html and default.html are the same now. So they can be removed. Also, the four other pages,namely __about.html__, __home.html__, __page.html__ and __post.html__ have the same content. They can be converted into one page as well. Your thoughts @YashKumarVerma ?

_Originally posted by @ShubhankarKG in https://github.com/CircuitVerse/Interactive-Book/pull/287#issuecomment-629599256_

### PR DESCRIPTION
**Pull request by ShubhankarKG**
Fixes #295 

#### Changes done:
- [x] Removed __about.html__, __home.html__, __page.html__, __page.html__ and __post.html__ as they weren't used anywhere in the site.
- [x] Removed kmap.html as default.html and kmap.html is the same. So, updated kmap.md to use default layout.

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ShubhankarKG** [comment]
Please review @YashKumarVerma

**Comment by YashKumarVerma** [comment]
> Please review @YashKumarVerma

sample link ?
if the link is not there, please do not check the option. :-1:

**Comment by ShubhankarKG** [comment]
Apologies. Here's the preview link :
https://5ec0e1f6b4e1120007caa4eb--tender-ardinghelli-ebb79f.netlify.app/

**Comment by YashKumarVerma** [comment]
Good work !

**Pull request merged**
