### PR TITLE
Fix dark mode button refresh bug

### LINKED ISSUE #376: Dark Mode Button does not works properly on refresh
## Describe the bug
Whenever the dark mode is selected by the user, on refreshing the page, Dark mode is retained but the text on the button switches back to Dark Mode instead of Light Mode.

## To Reproduce

1.  Go to 'https://learn.circuitverse.org/'
2.  Click on 'Dark Mode'
3.  Refresh The Page
4.  See error

## Expected behavior

It should display Light Mode Text on the button when Dark Mode is selected and the Page is refreshed.

## Desktop (please complete the following information):

* OS: [Windows 10]
* Browser [Chrome]

I am not working on this Issue. If anyone wants to work, Please comment below and this issue will be assigned to you 👍

### PR DESCRIPTION
**Pull request by b30wulffz**
Fixed dark mode refresh bug

Fixes #376 

#### Changes done:
- [x] Text now appears as usual on the button, even on refresh

#### Screenshots
Not needed

#### Preview Link(s): 
https://interactive-book.netlify.app/

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by b30wulffz** [comment]
@Shivansh2407 Please review

**Comment by b30wulffz** [comment]
@Shivansh2407 Sure. I didn't get that thing regarding preview link. Does it follow any specific format?

**Comment by Shivansh2407** [comment]
> @Shivansh2407 Sure. I didn't get that thing regarding preview link. Does it follow any specific format?

Not any specific format but the link is generated each time you open a PR. So it eases your work on the part of deployment so you do not need to deploy it from your side. It is better to post this link .

**Comment by b30wulffz** [comment]
@Shivansh2407 That's great. But from where can I get that generated link?

**Comment by Shivansh2407** [comment]
image
You get see that here 👍

**Comment by b30wulffz** [comment]
@Shivansh2407 Oh, I didn't know that before. That's amazing. Thank you.

**Pull request merged**
