### PR TITLE
added alert message for undefined values in table

### LINKED ISSUE #445: Show alert instead of undefined behavior.
Nice Work @b30wulffz 👍 
We Also need to fix the table generated after filling the drop-downs, as sometimes we get undefined. An alert should be displayed instead of showing undefined in the table. We need to do that in a different PR.

_Originally posted by @Shivansh2407 in https://github.com/CircuitVerse/Interactive-Book/pull/444#issuecomment-643951084_

### PR DESCRIPTION
**Pull request by animesh-007**
A meaningful title for PR, not like: made changes to xyz.md

Fixes #445 

Ref #

#### Changes done:
- [x] Added alert message

#### Screenshots
Screen Shot 2020-07-13 at 1 45 08 AM

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by animesh-007** [comment]
@YashKumarVerma Can you review this PR?

**Review by coding-CEO — APPROVED** [review]
Looks good to me. :+1:

**Comment by animesh-007** [comment]
@Shivansh2407 Can you review this PR?

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by YashKumarVerma** [comment]
Thanks a lot for your contributions.

**Pull request merged**
