### PR TITLE
truth table correction

### PR DESCRIPTION
**Pull request by rishabhgit0608**
https://learn.circuitverse.org/docs/bool2.html
2nd truth table is logically incorrect fixed this issue
Screenshot (243)

### CODE REVIEW

**Comment by aayush-05** [comment]
Please fix merge conflicts

**Comment by manjotsidhu** [comment]
@ayan-biswas0412 Can you take up this issue ?

**Comment by ayan-biswas0412** [comment]
@manjotsidhu sure

**Comment by ayan-biswas0412** [comment]
@manjotsidhu can you tell what should I do ? Fix the merge conflicts ?

**Comment by manjotsidhu** [comment]
> @manjotsidhu can you tell what should I do ? Fix the merge conflicts ? 

Yes

**Comment by ayan-biswas0412** [comment]
> > @manjotsidhu can you tell what should I do ? Fix the merge conflicts ?
> 
> Yes

image
Can you give me access to the repo such that I can pull it

**Comment by ayan-biswas0412** [comment]
> > > @manjotsidhu can you tell what should I do ? Fix the merge conflicts ?
> > 
> > 
> > Yes
> 
> image
> 
> Can you give me access to the repo such that I can pull it @manjotsidhu

**Comment by manjotsidhu** [comment]
> > > > @manjotsidhu can you tell what should I do ? Fix the merge conflicts ?
> > > 
> > > 
> > > Yes
> > 
> > 
> > image
> > Can you give me access to the repo such that I can pull it @manjotsidhu

You have to create a new Pull Request and fix conflicts.
You can cherry-pick the [commit](https://github.com/rishabhgit0608/Interactive-Book/commit/36fc009d408226738b5288c5693d2bae1d17b19f) or merge [this](https://github.com/rishabhgit0608/Interactive-Book/tree/newone) branch.

**Comment by ayan-biswas0412** [comment]
@manjotsidhu I think what user have done is , first pulling from master then make changes and then this PR is trying to aligning with our 'GSoD2020' branch but in the 'GSoD2020' branch many things have changed and there is no 'docs/bool2.md' now so I think the PR should be first aligned with the 'GSoD2020' branch

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please pull the ```GSoD2020``` branch first and then make your changes and do the PR 
I think you have worked on the master and now when trying to make PR with ```GSoD2020``` branch it gives the conflict

**Comment by manjotsidhu** [comment]
> please pull the `GSoD2020` branch first and then make your changes and do the PR
> I think you have worked on the master and now when trying to make PR with `GSoD2020` branch it gives the conflict

@ayan-biswas0412 the changes are based on GSoD2020 branch only but since it is a old PR, there have been significant changes on it due to which merge conflicts are happening. You can apply the same implementation on the branch and create PR. Location of `docs/boo12.md` is changed to `docs/binary-algebra/boolean-functions.md`.

**Comment by ayan-biswas0412** [comment]
> > please pull the `GSoD2020` branch first and then make your changes and do the PR
> > I think you have worked on the master and now when trying to make PR with `GSoD2020` branch it gives the conflict
> 
> @ayan-biswas0412 the changes are based on GSoD2020 branch only but since it is a old PR, there have been significant changes on it due to which merge conflicts are happening. You can apply the same implementation on the branch and create PR. Location of `docs/boo12.md` is changed to `docs/binary-algebra/boolean-functions.md`.

oak I will do a separate PR then

**Comment by ayan-biswas0412** [comment]
@manjotsidhu I have made the PR #532 please review it , I have ported the changes , please review that , I have kept the changes done in this PR , after merging my PR this PR can be closed

**Pull request closed without merging**
