### PR TITLE
Making Number of Comments Visible

### PR DESCRIPTION
**Pull request by Code2Magic**
Comments made visible in Dark Mode

### CODE REVIEW

**Comment by deepak2431** [comment]
@Code2Magic I think the changes you have done is good as I am not able to load disgus due to some error. 
@tachyons Please review once.

**Comment by tachyons** [comment]
But changes seems to have nothing to do with the original issue, @ShreyaPrasad1209 Can you please check verify the issue, In the first look it seems that original issue no longer exist

**Comment by Code2Magic** [comment]
@tachyons I can still see the original issue on Interactive Book page..Can you pls check it again 
https://learn.circuitverse.org/

**Comment by aayush-05** [comment]
@tachyons the problem is we can embed disqus only via its cdn and the official stylesheets doesn't seem to have support for dark mode. The "Interactive Book" tab is looking lighter only because it hasn't been selected at the moment, but you can see by toggling the modes, that no color of disqus elements changes.
Since, we don't have the option to put it in our assets folder, we might not be able to change the code.

**Comment by tachyons** [comment]
Can you please add the screenshots to clarify the issue

**Comment by Code2Magic** [comment]
Screenshot (206)

**Comment by Code2Magic** [comment]
Screenshot (207)
@tachyons  The colour of diqus  elements is not changed in dark mode..I think @aayush-05 wanted to explain this. Not sure though

**Comment by aayush-05** [comment]
Invalid issue, so this pr can be closed @tachyons

**Pull request closed without merging**
