### PR TITLE
Bread crumb overlap

### LINKED ISSUE #196: Overlapping 'Sidebar' button and 'breadcrumb-nav'
In https://learn.circuitverse.org/docs/Combinational/half_adder.html
and all the 'child' pages of `Combinational Circuits`  the `Sidebar` toggle switch and the `Breadcrumb-nav` used to navigate are overlapping.

Selection_024

**Are you working on it ?**
YES

### PR DESCRIPTION
**Pull request by vedangj044**
Fixed #196 
Selection_025

### CODE REVIEW

**Comment by vedangj044** [comment]
@tachyons please review and merge

**Comment by Ananthavijay** [comment]
@vedangj044 pls check whether there is movement of bread crumbs nav when the sidebar button is clicked

**Comment by vedangj044** [comment]
@Ananthavijay no the bread crumb nav stays where it is.

**Comment by Ananthavijay** [comment]
@vedangj044 so make it to move

**Comment by tachyons** [comment]
Thanks

**Pull request merged**
