### PR TITLE
ported the changes from the conflicted PR to GSoD2020 branch

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
A meaningful title for PR, not like: made changes to xyz.md
I have made necessary changes such that all the changes of the PR #484 remain same and it can be merged with ```GSoD2020``` branch

Fixes #484 

#### Changes done:
- [x] ported the changes from the conflicted PR to GSoD2020 branch

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@manjotsidhu please review

**Comment by manjotsidhu** [comment]
@ayan-biswas0412 boolean functions docs was changed in `GSoD2020` but also contents were moved to `docs/logic-design/canonical`

Check https://learn.circuitverse.org/docs/bool2.html#truth-table-formation
You just need to change the truth table in that part

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 boolean functions docs was changed in `GSoD2020` but also contents were moved to `docs/logic-design/canonical`
> 
> Check https://learn.circuitverse.org/docs/bool2.html#truth-table-formation
> You just need to change the truth table in that part

there is no as such truth table present in the ```GSoD2020``` so I have to copy the missing parts here

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 boolean functions docs was changed in `GSoD2020` but also contents were moved to `docs/logic-design/canonical`
> 
> Check https://learn.circuitverse.org/docs/bool2.html#truth-table-formation
> You just need to change the truth table in that part

ohh sorry I get it I have to change in canonical

**Comment by ayan-biswas0412** [comment]
@manjotsidhu please review I have made the necessary changes

**Review by manjotsidhu — APPROVED** [review]

**Comment by manjotsidhu** [comment]
@Shivansh2407 Kindly review and merge this.

**Pull request merged**
