### PR TITLE
Fix flipflop state table

### PR DESCRIPTION
**Pull request by JyothsnaAshok**
Issue #142 
GCI Task Link- [Instance](https://codein.withgoogle.com/dashboard/task-instances/5249296392257536/)
Preview [Link](https://deploy-preview-193--tender-ardinghelli-ebb79f.netlify.com/docs/flipflop2.html)

## Description

- I've changed the OR , AND & NOT operations.
- I've also changed the column heading for the next state as it is confusing for new users.

## Screenshots of Changes
d flipflop

image

image

### RS Flip FLop
image

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@JyothsnaAshok I think the problem exists with T and JK flip flop only. If you have fixed it, update the screenshots with T and JK flip flop.

**Comment by sakshi1499** [comment]
Look at the recent pull request made for jk and t flip flop, you will see that I asked the participant to add hints as to what input we should feed. So add that and then put its screenshot in the description. @JyothsnaAshok

**Comment by JyothsnaAshok** [comment]
@sakshi1499  Okay!

**Comment by JyothsnaAshok** [comment]
@sakshi1499 I've added the Hints for User input.

image

image

image

**Comment by aayush-05** [comment]
Great job @JyothsnaAshok . But since we received mutiple prs for this issue, only one needs to be merged. This can be closed @tachyons

**Pull request closed without merging**
