### PR TITLE
GSoD2020 Interactive Book Sequential logic chapters

### PR DESCRIPTION
**Pull request by danielluehr**
Most sections for the sequential logic chapters are done.

#### Changes done:
- [x] Sequential LSI chapter complete. More interactive examples in progress, will be added to the next PR
- [x] Sequential design chapter complete.
- [ ] Sequential SSI chapter mostly complete. Medium level sections missing, part of the content is available from the current version of the book but it is scattered in other sections. Will be fixed in the next PR.
- [ ] Sequential MSI chapter mostly complete. Medium level section are still WIP. Will be included in the next PR

### CODE REVIEW

**Review by Shivansh2407 — CHANGES_REQUESTED** [review]
@danielluehr here, it is showing 104 commits, which I guess it has taken up from the start of GSoD, while for this PR, there are recent 3 commits. Please check and update the PR so that we can merge this

**Comment by danielluehr** [comment]
> @danielluehr here, it is showing 104 commits, which I guess it has taken up from the start of GSoD, while for this PR, there are recent 3 commits. Please check and update the PR so that we can merge this

I see... I chose the wrong branch for the PR. Let me see if I can find out how to amend the PR.

**Comment by danielluehr** [comment]
> > @danielluehr here, it is showing 104 commits, which I guess it has taken up from the start of GSoD, while for this PR, there are recent 3 commits. Please check and update the PR so that we can merge this
> 
> I see... I chose the wrong branch for the PR. Let me see if I can find out how to amend the PR.

Ok, this is strange... I followed the instructions (edit PR, change base branch) but it says the following:
A pull request already exists for base branch 'GSoD2020' and head branch 'GSoD2020' 
And it goes back to the master branch... maybe the same happened when I submitted the PR earlier and I didn't notice.

I don't know why now it is not merging my previous PR with this one... maybe because there are 2 other PR from another user in between and for the same branch (?).

I guess the previous one #485 should be merged first? And then I can edit and submit this one?

**Comment by satu0king** [comment]
@danielluehr if you added commits to the previous branch, your PR automatically gets updated - check if this PR is updated - https://github.com/CircuitVerse/Interactive-Book/pull/485

**Comment by danielluehr** [comment]
> @danielluehr if you added commits to the old branch, your old PR automatically gets updated - check if this PR is updated - #485, You can simply close this PR then.

Yes :-) The commits are in the #485. Should I cancel PR #490?

**Comment by satu0king** [comment]
> > @danielluehr if you added commits to the old branch, your old PR automatically gets updated - check if this PR is updated - #485, You can simply close this PR then.
> 
> Yes :-) The commits are in the #485. Should I cancel PR #490?

Yes, closing it

**Pull request closed without merging**
