### PR TITLE
Fixed responsiveness and redesigned UI of Binary to Decimal Converter

### LINKED ISSUE #416: Extremely small size of binary to decimal converter in mobile devices
## Describe the bug

Binary to decimal converter becomes extremely small when opened in mobile devices. As well as, the UI of the tool does not match with the theme.

## To Reproduce

1.  Go to https://learn.circuitverse.org/docs/binary.html on any mobile device or emulate it using Google Chrome
2.  Scroll down to end of the page (up to Binary to Decimal converter tool)
3.  See error

## Expected behavior

Binary to Decimal converter tool should be responsive.

## Screenshots

mobileB

Note: Screen size of Google Pixel 2 XL emulated using Inspect Element on Chrome

## Desktop (please complete the following information):

* OS: Windows 10
* Browser: Chrome
* Version: 83.0.4103.97

## Smartphone (please complete the following information):

* Device: Poco Phone F1
* OS: Android 10
* Browser: Chrome
* Version: 80.0.3987.132

## Additional context

Upon seeing the code of binary.html, I found that sizes including font-size were hardcoded with respect to viewport width which is wrong considering this use case.

### PR DESCRIPTION
**Pull request by b30wulffz**
Fixed responsiveness and redesigned UI of Binary to Decimal Converter.

Fixes #416  

#### Changes done:
- [x] Rewrote CSS code for tool
- [ ] Made tool responsive for different screen sizes

#### Screenshots

- Light UI

lightUI

- Dark UI

darkUi

- Mobile Screen Size

mobile

#### Preview Link(s): 
[https://interactive-book.netlify.app/docs/binary.html](https://interactive-book.netlify.app/docs/binary.html)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Shivansh2407** [comment]
We need to update these changes with the binary2.html page too 👍.

**Comment by b30wulffz** [comment]
@Shivansh2407 @abhinavsri360 @YashKumarVerma Thanks for the feedback! Working on placing = sign. Will definitely work on binary2.html after this is completed.

**Comment by b30wulffz** [comment]
> Looks great @b30wulffz Some changes I would like to suggest.
> 
> * place the equal sign in a different box followed by the decimal equivalent box.
> * Add binary as a word somewhere in starting, refer the photo below for the same.
>   image
>   Let me know your views on the same.
>   Your changes look awesome anyways 😄

Writing Binary on that portion is possible, but the issue is with the Decimal heading, as it should also on the same level. Otherwise, it would look a little different.

**Comment by b30wulffz** [comment]
I have planned to remove = completely as the UI is looking bad after it. Instead changed background that is suiting well.
image

**Comment by abhinavsri360** [comment]
> > Looks great @b30wulffz Some changes I would like to suggest.
> > 
> > * place the equal sign in a different box followed by the decimal equivalent box.
> > * Add binary as a word somewhere in starting, refer the photo below for the same.
> >   image
> >   Let me know your views on the same.
> >   Your changes look awesome anyways 😄
> 
> Writing Binary on that portion is possible, but the issue is with the Decimal heading, as it should also on the same level. Otherwise, it would look a little different.

Can I have a look at that different look? Snippet probably.

**Comment by b30wulffz** [comment]
> > > Looks great @b30wulffz Some changes I would like to suggest.
> > > 
> > > * place the equal sign in a different box followed by the decimal equivalent box.
> > > * Add binary as a word somewhere in starting, refer the photo below for the same.
> > >   image
> > >   Let me know your views on the same.
> > >   Your changes look awesome anyways 😄
> > 
> > 
> > Writing Binary on that portion is possible, but the issue is with the Decimal heading, as it should also on the same level. Otherwise, it would look a little different.
> 
> Can I have a look at that different look? Snippet probably.

Sure I have to code that different look😁 Will send soon.

**Comment by b30wulffz** [comment]
@abhinavsri360 Added! If you approve then I will send PR with updated code.
image

**Comment by abhinavsri360** [comment]
Looks awesome @b30wulffz 
Before pushing changes wait for this to be approved by @Shivansh2407 and @YashKumarVerma 
In my opinion, this looks cool

**Comment by b30wulffz** [comment]
I haven't made a PR for this yet. Please confirm which one looks better: 

1. without binary
1. with binary: image 1
1. with binary: image 2: with lower position

Then I would push changes 🙂

**Comment by abhinavsri360** [comment]
> I haven't made a PR for this yet. Please confirm which one looks better:
> 
> 1. without binary
> 2. with binary: image 1
> 3. with binary: image 2: with lower position
> 
> Then I would push changes 🙂

In my opinion, I would prefer the second option. Let's wait for others to have a vote on this.

**Comment by YashKumarVerma** [comment]
> I haven't made a PR for this yet. Please confirm which one looks better:
> 
> 1. without binary
> 2. with binary: image 1
> 3. with binary: image 2: with lower position
> 
> Then I would push changes

2. looks good to me. 
Plus, when you make changes, push the code as well. So that if there are any changes that should be done in it, it can be told then itself.

Good work, push the changes now.

**Comment by b30wulffz** [comment]
Pushed ✌ It can be checked on [https://interactive-book.netlify.app/docs/binary.html](https://interactive-book.netlify.app/docs/binary.html)

Just a small doubt: @YashKumarVerma 

>    Plus, when you make changes, push the code as well. So that if there are any changes that should be done in it, it can be told then itself.

Won't it lead to a lot of commits in the issue?

**Comment by Shivansh2407** [comment]
> Added some comments which might be helpful and pushed  It can be checked on https://interactive-book.netlify.app/docs/binary.html
> 
> Just a small doubt: @YashKumarVerma
> 
> > Plus, when you make changes, push the code as well. So that if there are any changes that should be done in it, it can be told then itself.
> 
> Won't it lead to a lot of commits in the issue?

Yes it would lead to a lot of commits, but then you need to squash them. Please make sure you squash the commits and then mark it as done in the template.
You've done really an awesome job here @b30wulffz 👍.

**Comment by b30wulffz** [comment]
@Shivansh2407 Yeah squashed these commits into one.
Thank you 😊

**Comment by Shivansh2407** [comment]
Nice Work @b30wulffz 👍 .

**Pull request merged**
