### PR TITLE
Add previous and next buttons to all pages (Fixes #73 and same as #160)

### LINKED ISSUE #73: Add Next and Prev option
**Problem**
Right now there's no link(apart from side navbar) which directs user from one page to another. Like in a book we can turn to next/prev page, we can do this in Interactive Book too.

**Proposed Solution**
Add a Next and Prev link in each page which will redirect the user to relevant page.
**Screenshot** 

Add this link above comment section

**Are you working on this task?**
No, for GCI participants under medium

### PR DESCRIPTION
**Pull request by JoshHeng**
An duplicate of #160 (as the branch there got too messy)

Fixes #73

Added previous and next buttons which allow the user to advance through the whole interactive book with one button.

### CODE REVIEW

**Comment by JoshHeng** [comment]
@Shivansh2407 Please review

**Comment by abhinavsri360** [comment]
Deployment link?

**Comment by JoshHeng** [comment]
@ab

> 
> 
> If possible can you append these buttons at the bottom of the page as well? I guess that will be an asset for the user as a reader reads from top to bottom and scrolling back to the top might not look friendly.

👍

**Comment by JoshHeng** [comment]
> 
> 
> Please update your PR description with screenshots of the changes made and preview link.
@Dishebh 

The changes made can be previewed with the Netlify Deploy Preview (one of the checks). I've also added a screenshot to the original PR description

**Comment by JoshHeng** [comment]
> 
> 
> Quick question: are you submitting this pr for GSoD ?
> 
> If yes, then there are two changes that I would recommend
> 
>     * I think the two buttons must be of the same size as the above ones [question]. (I know this was done intentionally as the sidebar button is of the same size)
>       image
> 
>     * The ones at the bottom should be on the right side as well.
>       image
> 
> 
> If no, then there's no need to make the above changes. We value every contribution.

I'm not doing GSoC but I joined CircuitVerse earlier this year for GCI.
I think the button size should be kept the same so it's the same as the sidebar button

**Comment by YashKumarVerma** [comment]
views regarding right alignment ?

**Comment by JoshHeng** [comment]
> 
> 
> Please fix the merge conflicts @JoshHeng . A small suggestion, we can keep the next button on right and previous button on the left side. Also keep it just above the Disqus Comments. Let me know your views @YashKumarVerma

Done

**Comment by YashKumarVerma** [comment]
Thanks !

**Pull request merged**
