### PR TITLE
Refactor the Disqus Code

### PR DESCRIPTION
**Pull request by JoshHeng**
Removed all instances of `{% include disqus.html %}` and moved it to `default.html`

This is because it is bad practise to repeat code which could just be added to the default layout. Some random pages didn't have Disqus (probably because the author forgot to copy the code in).

The Disqus commenting code has been refactored from in each page's file to the default layout.
Commenting can be disabled by adding `page.disable_comments` to true

Reference #171

### CODE REVIEW

**Comment by mohit-003** [comment]
This causes a problem in Flip-Flops page and also some other pages please check it once.

**Comment by JoshHeng** [comment]
@mohit-003 What problems are you referring to?
Although on the Flip-Flops page commenting is not shown, it also wasn't shown originally (however I admittedly don't know what is causing this)

Do you want me to investigate? Do we want commenting on all pages?

**Comment by mohit-003** [comment]
> (however I admittedly don't know what is causing this)

I think in the docs/the_file comments should be given true. 
> Do we want commenting on all pages?

In my opinion it might be better to have comments on all the pages.
> Removed all instances of {% include disqus.html %} and moved it to default.html

But yes this is better than having it in all pages 👍

**Comment by aayush-05** [comment]
@JoshHeng Try adding the disqus link in other layouts as well. Some pages are using the kmap layout as well.

**Comment by aayush-05** [comment]
@JoshHeng are you still working on this ?

**Comment by JoshHeng** [comment]
> 
> 
> @JoshHeng are you still working on this ?

I can if more needs doing?

**Comment by JoshHeng** [comment]
Fixed, please merge

**Pull request merged**
