### PR TITLE
Select input is now visible in Dark Mode

### LINKED ISSUE #246: Search text is not visible in Dark Mode
Screenshot 2020-03-16 at 1 03 56 AM
Screenshot 2020-03-16 at 1 04 15 AM

Solution : Add conditionals and change text color according to mode selected.

I am working on this issue.

### PR DESCRIPTION
**Pull request by pranavmodx**
fixes #246

### CODE REVIEW

**Comment by pranavmodx** [comment]
fixes #246

**Comment by aayush-05** [comment]
Can you add appropriate screenshots @pranavmodx ?

**Comment by Shivansh2407** [comment]
Yes Please add the screenshots @pranavmodx . It is not working in the deployed preview . Please Check Once.

**Comment by coding-CEO** [comment]
This solution actually changes the background of search bar to white. Which don't suit the Dark Mode.
Checkout my solution #320 .
@YashKumarVerma @Shivansh2407 @aayush-05

**Comment by Shivansh2407** [comment]
Closing this as #320 provides a better solution for the issue.

**Pull request closed without merging**
