### PR TITLE
removed redundant data and made alu.md prettier

### PR DESCRIPTION
**Pull request by Dishebh**
### Changes done:
- [x] Removed redundant data and made `alu.md` file more prettier.

Preview Link: https://deploy-preview-300--tender-ardinghelli-ebb79f.netlify.app/

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Dishebh** [comment]
> Could you list down the improvements done in this PR ?

Sure.

- Removed some redundant text.
- Corrected some grammatical errors.

**Comment by YashKumarVerma** [comment]
> > Could you list down the improvements done in this PR ?
> 
> Sure.
> 
> * Removed some redundant text.
> * Corrected some grammatical errors.

Kindly update the pr title with something of that sort.

**Comment by Shivansh2407** [comment]
Nice Work @Dishebh 👍. But Please Keep In mind to change the preview URL redirecting to the Page which you have changed. Like for this PR the preview URL should be : https://deploy-preview-300--tender-ardinghelli-ebb79f.netlify.app/docs/alu.html . 
I have added some changes to the alu.md file too.

**Comment by Dishebh** [comment]
> Nice Work @Dishebh . But Please Keep In mind to change the preview URL redirecting to the Page which you have changed. Like for this PR the preview URL should be : https://deploy-preview-300--tender-ardinghelli-ebb79f.netlify.app/docs/alu.html .
> I have added some changes to the alu.md file too.

Sure, will take care of it next time. Thanks!

**Pull request merged**
