### PR TITLE
Make the table generated by "Truth Table Generator" responsive

### LINKED ISSUE #94: Make table generated by "Truth Table Generator" responsive
#### I am submitting a -
* **Bug Report**

#### Describe your bug/feature -
When the number of inputs is large, the table generated by the truth table generator goes out of the page.

#### Current behaviour -
Table goes out of page.

#### Expected behaviour -
Table should be responsive, have a scroll bar.

#### Screenshots (if relevant) -
Screenshot from 2019-11-29 04-32-16

#### Are you working on this issue? (Yes/No)
Nope. For GCI 2019

### PR DESCRIPTION
**Pull request by JamesT44**
This is my submission to the GCI task for this issue. My username on the GCI site is Bubble Sort. This is the new functionality:

image

Resolves #94

### CODE REVIEW

**Comment by JamesT44** [comment]
How's this?

**Comment by sal2701** [comment]
Hey @JamesT44! On the GCI dashboard, once you abandon a task, it becomes open for others to claim it. Someone else has claimed it since you had abandoned it yesterday. Sorry but I can only consider the contributions of the person who claimed the task since this a GCI issue and we need to work according to the GCI Dashboard. Don't worry but you can find other tasks to work on. Also if the other person isn't able to complete the task, you can surely claim the task again :slightly_smiling_face:

**Comment by JamesT44** [comment]
Yeah I didn't realise you had written something here, so I moved on. Glad to help though.

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed, fixed in #195

**Comment by Shivansh2407** [comment]
Fixed in #195

**Pull request closed without merging**
