### PR TITLE
[GCI] Added correct implementation of Half-Adder

### LINKED ISSUE #43: Add types of Asynchronous and Synchronous counter
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
The types of asynchronous and synchronous is missing in the book which should be added.

### LINKED ISSUE #113: Half-Adder Interactive Circuit
https://learn.circuitverse.org/docs/Combinational/half_adder.html

The circuit embedded in the above link uses the built in adder and is therefore wrong. Replace it with a correct implementation of the half-adder circuit.

### PR DESCRIPTION
**Pull request by JyothsnaAshok**
Fixes #113  Half-Adder Interactive Circuit
### Description
I've replaced the embedded circuit with a correct implementation of the half-adder circuit.

### Screenshots of Changes (if any)
image

Preview: https://circuitverse.org/users/14177/projects/43463

GCI Task Instance: https://codein.withgoogle.com/dashboard/task-instances/5868156627714048/

### CODE REVIEW

**Comment by sakshi1499** [comment]
@JyothsnaAshok can you please recheck, I think its not fixing issue 43 but some other issue. Please update that

**Comment by sakshi1499** [comment]
Also your task instance is also showing asynchronous and synchronous counter and here you are working on half adder

**Comment by deepak2431** [comment]
@JyothsnaAshok Great work. 
@sakshi1499 @eKuG Please review it.

**Comment by sakshi1499** [comment]
@deepak2431 I have suggested some changes please let them be done first. Rest regarding the circuit, please also include preview of your interactive circuit? @JyothsnaAshok

**Comment by deepak2431** [comment]
@sakshi1499 Yeah, sure. I haven't seen your comment before so I asked you to review it once :)

**Comment by JyothsnaAshok** [comment]
@sakshi1499 I've made the required changes. Please have a look. :)

**Comment by sakshi1499** [comment]
I also asked you to add the preview to your circuit in the description. Please add that too. It looks good otherwise😊 @JyothsnaAshok

**Comment by sakshi1499** [comment]
@eKuG @deepak2431 It looks good to me, you also review once 😊

**Comment by eKuG** [comment]
seems good enough.

**Comment by deepak2431** [comment]
@sakshi1499 Looks good to me too.

**Comment by sakshi1499** [comment]
Lets approve it then? Good work! 😊

**Comment by deepak2431** [comment]
@sakshi1499 Yeah sure you can approve her task now.

**Comment by aayush-05** [comment]
@tachyons looks good to be merged

**Pull request merged**
