### PR TITLE
Changing colours

### PR DESCRIPTION
**Pull request by namantechlabs**
Changing colours according to Issue #52 for GCI :)

### CODE REVIEW

**Comment by aayush-05** [comment]
@tachyons @ankitkataria 
Do review this pull request. Student did the changes as per the screenshots.
We can even have different color theme if you guys suggest.

**Comment by aayush-05** [comment]
@tachyons The pr is changing the values of sass variables which is to be further used in all the pages.
They have already been defined.

**Comment by tachyons** [comment]
I mean give some readable name for those colors

**Comment by namantechlabs** [comment]
I don't think that there are any readable names for the colours used.

**Comment by aayush-05** [comment]
But standard colour names aren't available for the colours mentioned in the issue, so instead hex values has been used.

**Comment by aayush-05** [comment]
Do review this again @tachyons 
The colors mentioned in the issue are not having any standard names, so I think hexvalues would be fine.

**Pull request merged**
